---
title: "Uvod"
---

Iako je komunikacija jedno od suštinskih određenja ljudske vrste, komunikacijska znanost ili komunikologija kao interdisciplinarna znanost koja istražuje najraznovrsnije oblike komuniciranja između živih bića, a obuhvaća proučavanje sadržaja, oblika i tehnika priopćavanja, istraživanje smisla poruka i načina njihova prihvaćanja te učinka poruka što protječu između pošiljatelja i primatelja (enciklopedija.hr)[^1], jedna od najmlađih društvenih znanosti.

Kao samostalna disciplina koja „proučava komunikaciju kao temeljni socijalno-psihološki proces kroz njezine funkcije (stvaranje promjena u prolazu kroz kanal), uzročnike (znakove, simbole) i smetnje" (Mataušić, 2007:23), komunikologija se počinje razvijati u prvoj polovini dvadesetog stoljeća. Razvija se paralelno s pojavom i razvojem medija masovnih komunikacija, prvenstveno u SAD i to kao praktična, u prvom redu primijenjena društvena znanost. Kuncznik i Zipfel (2006:32) navode da se korijeni američke komunikologije, koja je utjecala na europsku, nalaze u rješavanju praktičnih problema kao što su pitanje ekonomskog kao i vojnog te političkog korištenja propagande. Postulirana na taj način, komunikologija se u početnoj fazi svog razvoja pretežito bavila medijskim učincima na individualnoj razini, tj. istraživane su reakcije manje ili više izoliranih pojedinaca ili malih skupina na masmedijske sadržaje (Kuncznik i Zipfel, 2006:35). Danas je središnja os istraživanja medija i komunikacije ona koja se bavi složenim odnosom između medijske proizvodnje i medijske recepcije (Bilić, 2020:31).

Od prvih dana svoga utemeljenja pa do danas, komunikologija je generirala opsežnu količinu znanja o tome kako mediji utječu na stavove i ponašanje ljudi, o praksama medijske konzumacije kao i o modalitetima medijskih utjecaja na različite društvene procese. Drugim riječima, brojna istraživanja koja su provodili i koje provode komunikolozi diljem svijeta rezultirala su i izgradnjom brojnih teorija o suodnosu medija, društva i pojedinaca. Taj spremnik komunikološkog znanja u najvećoj mjeri ispunjen podacima prikupljenim empirijskim istraživanjima. Naime, jedno od dominantnih određenja komunikologije ono je koje ju definira kao suštinski empirijsku društvenu znanosti. Riječ je o društvenoj znanosti koja je od svojih početaka generirala empirijski utemeljene teorijske koncepte i koja o svojem predmetu govori primarno posredstvom empirijskih podataka. Razlozi ovakvog, empirijskog statusa komunikologije kao znanosti mogu se potražiti u tome što se ona razvija kasnije od većine društvenih znanosti te je stoga od svojih početaka bila u prilici koristiti različita metodološka rješenja razvijena u okviru starijih društvenih znanosti, kao što se mogu potražiti i u multidisciplinarnosti izvorišta ranih komunikoloških istraživanja. Naime, utemeljitelji komunikologije osobe su koje su bazične znanstvene kompetencije stekli na različitim znanstvenim područjima. Primjerice među utemeljiteljima komunikologije su sociolozi Lazarsfeld, Merton i Katz, psiholog Hovland, filozof i ekonomist Laswell te politolog Scharamm.

Dakle, usmjerenost na bavljenje empirijski opažljivim fenomenima kao i mogućnost da ih se proučava iz različitih disciplinarnih perspektiva pred komunikologe postavlja i zahtjeve solidnog metodološkog obrazovanja. Poznavanje metoda društvenih istraživanja koje se koriste u istraživanju komunikoloških fenomena, bilo da je riječ o akademskim ili primijenjenim istraživanjima za akademski obrazovane komunikologije sastavni je i nužni sadržaj „kutije" u kojoj je pohranjen njihov strukovni alat. Proučavati medije, pogotovo u vremenu kada mediji više nisu isključivo TV, radio i tisak, već i društvene mreže, podcasti, blogovi i vlogovi, alogritim i softveri, a pri tom se ne referirati na empirijske podatke danas je gotovo nezamislivo. To je posebice važno stoga što su suvremeni digitalni mediji i algoritamski posredovana komunikacija ušli u gotovo sve pore egzistencije većine ljudi te mediji više ne djeluju samo kao sredstvo informiranja, obrazovanja i zabave, već i kao ključni instrument oblikovanja dinamike zbivanja u društvenim, političkim i kulturnim sferama. Stoga se i suvremena komunikologija više ne može zadržati isključivo na svojem utemeljiteljskom određenju – kao znanost koja proučava oblike komunikacije, sadržaje i tehnika priopćavanja, istraživanje značenja poruka i načina njihova učinka, već je riječ o znanosti koja istražuje kompleksne odnose između tehnologija, kulture, društva i komunikacije. Njihovo razumijevanje gotovo je nemoguće bez upotrebe seriozne metodologije znanstvenog istraživanja.

Ova knjiga zamišljena je kao svojevrsno „uputstvo za upotrebu" metodološkog strukovnog alata kojim raspolaže komunikacijska znanost. Iako je prvenstveno namijenjena studentima komunikacijskih znanosti, kako bi se na sustavan i metodičan način mogli familijarizirati s osnovnim metodama empirijskih društvenih istraživanja, ona će biti korisna i studentima sociologije, politologije, pedagogije, informacijskih znanosti kao i svima onima koji žele razumjeti, primijeniti ili unaprijediti svoje metodološko znanje, bilo u svrhu istraživanja fenomena masovne komunikacije, bilo u svrhu istraživanja drugih društvenih pojava i procesa.

Dakle, riječ je o svojevrsnoj metodološkoj početnici koja će omogućiti zainteresiranim čitateljim da se na jedan pregledan i sustavan način upoznaju s osnovnim metodološkim tradicijama, pojmovima i metodskim principima svojstvenim za empirijska istraživanja u društvenim znanostima.

[Knjiga je rezultat (OVO ĆEMO POMIJENITI) mog nastavnog rada na Odsjeku za komunikologiju na Fakultetu hrvatskih studija Sveučilišta u Zagrebu na kojem već više od deset godina predajem metodološke kolegije kao i mojeg praktičnog istraživačkog iskustva. Naime, više od dvadeset godina radio sam u privatnom sektoru na poslovima primijenjenih društvenih istraživanja – socioekonomskih, medijskih i tržišnih istraživanja kao i istraživanja javnog mnijenja. U više od 400 istraživačkih projekata u kojima sam sudjelovao koristio sam brojne tehnike i metode istraživanja – od ankete i analize sadržaja do intervjua, fokus grupa i etnografske metode. Stoga je knjiga koju držite u ruci suma mog teorijskog i praktičnog znanja o metodologiji društvenih istraživanja kao i specifičnostima u realizaciji onih metoda koje se, posebice u komunikacijskim znanostima, danas najčešće koriste – bilo u znanstveno-akademskim bilo u primijenjenim istraživačkim projektima. Razumljivo, ona je u jednom dijelu komplementarna s drugim dijelima koja obrađuju temu metoda istraživanja u društvenim znanostima budući da su njihova obilježja kao i metodska pravila univerzalne naravi, no s druge strane njena specifičnost možda je u činjenici što su je u njoj predstavljen i niz „uputstava za upotrebu", tj. praktičnih savjeta o tome na što sve treba obratiti pažnju prilikom korištenja pojedinih metoda istraživanja. Dakle, vodio sam se za idejom da uz spoznajno teorijsku pozadinu, kao i ključna metodološka obilježja svake od predočenih metoda istraživanja, predstavim i osnovna izvedbena pravila važna za njihovo prakticiranje. Naime, čini mi se da su metodološki udžbenici koji dolaze iz akademske sfere često opterećeni teorijsko-metodološkim načelima, dok onima koji dolaze iz sfere primijenjenih društvenih istraživanja često nedostaje dublje teorijsko-metodološke refleksije. Ovom knjigom pokušao sam to pomiriti.

Knjiga je organizirana kroz jedanaest poglavlja. U prvom dijelu obrađuju se osnovna obilježja znanosti i znanstvenog istraživanja, ciljevi znanstvenih istraživanja, razgraničuje se znanost od pseudoznanosti, upućuje se na proces razvoja znanosti te se predočava sistematizacija znanosti i znanstvenih istraživanja. Nakon toga govori se o razvoju komunikologije, njenim utemeljitelja i prvim empirijskim istraživanjima u njenom okrilju. Potom se prezentiraju osnovna obilježja metoda istraživanja u društvenim znanostima te spoznajno-teorijske osnove kvantitativnih i kvalitativnih metoda istraživanja. Najveći dio sadržaja knjige otpada na obradu onih metode istraživanja koje se učestalije koriste, bilo u okviru akademskih, bilo u okviru primijenjenih komunikoloških istraživanja: ankete, analize sadržaja, intervjua i fokus. Kako bi se bolje opisale i objasnile pojedine metodske propozicije navedenih metoda istraživanja u skripti su predočeni i brojni primjeri konkretnih komunikoloških empirijskih istraživanja. Zadnje poglavlje obrađuje problematiku tzv. mješovitog pristupa.
