# Osnovna obilježja znanosti i znanstvenog istraživanja

Znanost je jedan od mogućih pristupa u spoznavanju svijeta (Milas, 2009:4). Na najopćenitoj
razini moglo bi se ustvrditi da je znanost način spoznaje prirodnog ili društvenog svijeta koji se
temelji na empirijskim (opažljivim) činjenicama koje su prikupljene posredstvom specifičnih
postupaka (znanstvena metoda).
U znanstvenoj literaturi postoji veliki broj podrobnijih određenja znanosti. Primjerice, Milas
(2009:5) ističe da se u nekim slučajevima znanost poistovjećuje s mnoštvom činjeničnih
spoznaja prikupljenih u cjelinu, ponekad s objektivnim istraživanjem iskustvenih pojava,
ponekad s posebnim stavom što ga znanost zauzima prema stvarnosti. U jednom širem smislu,
znanost se može odrediti kao spoznaja prirodnih i društvenih pojava te njihovih uzroka do
kojih se dolazi na temelju opažljivih činjenica - empirijskih podataka. Može se definirati i kao
misaona interpretacija objektivne stvarnosti koja je zasnovana na činjenicama te stvarnosti
(Vujević, 2006:6). Načelno, možemo reći da većina određenja znanosti naglašavaju njena
sljedeća svojstva (Wimmer i Dominick, 2010:11-13):
1. Znanost je javna djelatnost – rezultati znanstvenih istraživanja ne smiju ostati tajne, tj.
ne smiju ostati privatno vlasništvo samog znanstvenika, već se moraju predočiti
javnosti.
2. Znanost je objektivna spoznaja svijeta – interpretacije i zaključci ne smiju biti pod
utjecajem stavova, vrijednosti ili nekih drugih subjektivnih svojstava znanstvenika.
3. Znanstvena spoznaja je empirijska – temelji se na činjenicama, a ne na spekulacijama.
4. Znanost je sustavan i kumulativan proces – u znanosti je važna nadogradnja znanja,
nove pojedinačne činjenice se nikada ne promatraju same za sebe već uvijek u jednom
širem korpusu znanja koje je razvijeno u okviru neke znanstvene discipline u prošlosti.
5. Znanost je prediktivna – znanost pokušava predvidjeti na koji će se način pojave i
fenomeni koje proučava zbivati u budućnosti.
Suštinu znanstvene spoznaje određuje priroda njenog predmeta i njenih metoda. Dok
prirodne znanosti svoj predmet definiraju kao materijalni svijet tj. materijalnu prirodu,
društvene znanosti svoj predmet definiraju kao rezultat ljudskih interakcija i društvenih
odnosa. Kroz interakcije i društvene odnose nastaju fenomeni i pojave koje proučavaju
sociologija, ekonomika, povijesne znanosti, antropologija, komunikologija. Primjerice, neki od

predmeta suvremenih društvenih znanosti su utjecaj medija na demokratske procese,
društvene nejednakosti, društvene vrijednosti, politički odnosi, ekonomski razvoj, društvena
stratifikacija, geopolitički odnosi itd. Shodno tome, može se konstatirati da je prvi preduvjet
znanosti postojanje predmeta znanstvenog istraživanja. On se može definirati kao dio
prirodnog ili društvenog svijeta koji je empirijski istraživ, tj. kao entitet o čijim se svojstvima
mogu donijeti zaključci temeljem opažljivih činjenica, a koji je predmet interesa znanstvenika.
Izbor predmeta istraživanja prvi je ključni moment u provođenju znanstvenog istraživanja.
Drugi ključni element znanstvenog istraživanja jest primjena znanstvene metode. Sam termin
potječe od grčke riječi methodos, što u doslovnom prijevodu znači put, čime se sugerira da je
metoda sustavno isplaniran proces koji istraživača vodi prema krajnjem cilju – valjanoj
spoznaji. U užem smislu, riječ metoda podrazumijeva skup propisanih procedura koje
znanstvenicima omogućuju znanstvenu spoznaju. Milas navodi da se primjenom znanstvene
metode prilikom spoznavanja prirodnog ili društvenog svijeta nastoji osloboditi ljudske
subjektivnosti i proizvoljnosti (Milas, 2009:5).
Sumirajući razlike između znanstvenog i neznanstvenog pristupa proučavanju prirodnog i
društvenog svijeta, ovaj autor izdvaja sljedeće odrednice znanstvene spoznaje:
Tablica 1. Odlike znanstvenog i neznanstvenog pristupa
Neznanstveni pristup Znanstveni pristup
Opći pristup Intuitivan, zdravorazumski Empirijski
Opažanje Prigodno, nesustavno, bez kontrole Sustavno, kontrolirano
Izvještavanje Subjektivno Objektivno
Definicije Nejasne, dvosmislene Jasne, operacionalne
pojmova
Instrumenti Netočni, neprecizni Točni, precizni
Mjerenje Nevaljano i nepouzdano Valjano i pouzdano
Pretpostavke Neprovjerljive Provjerljive
Zaključci Subjektivni, osobni, nadilaze objektivne Utemeljeni na podacima
podatke
Stav Nekritičan Kritički, skeptičan
Izvor: Milas (2009: 11)
Shodno svemu navedenom znanost se može definirati kao sustavni i kontrolirani postupak
spoznaje prirodnog ili društvenog svijeta posredstvom provjerljivih empirijskih činjenica do
kojih se dolazi korištenjem znanstvene metode.
