---
title: "Znanost i znanstvena spoznaja"
---

Znanost je jedan od mogućih pristupa spoznavanju svijeta (Milas, 2009:4). Na najopćenitoj razini mogli bismo reći da je znanost način spoznaje prirodnog ili društvenog svijeta koji se temelji na empirijskim (opažljivim) činjenicama koje su prikupljene posredstvom specifičnih postupaka (znanstvena metoda).

U znanstvenoj literaturi postoji veliki broj podrobnijih određenja znanstvene spoznaje. Primjerice, Milas (2009:5) ističe da se u nekim slučajevima znanost poistovjećuje s mnoštvom činjeničnih spoznaja prikupljenih u cjelinu, ponekad s objektivnim istraživanjem iskustvenih pojava, ponekad s posebnim stavom što ga znanost zauzima prema stvarnosti. U jednom širem smislu, znanost se može odrediti kao spoznaja prirodnih i društvenih pojava te njihovih uzroka do kojih se dolazi na temelju empirijskih podataka. Može se definirati i kao misaona interpretacija objektivne stvarnosti koja je zasnovana na činjenicama te stvarnosti (Vujević, 2006:6). Načelo, možemo reći da većina određenja znanosti naglašavaju njena sljedeća svojstva (Wimmer i Dominick, 2010:11-13):

1.  Znanost je javna djelatnost – rezultati znanstvenih istraživanja ne smiju ostati tajne, tj. ne smiju ostati privatno vlasništvo samog znanstvenika, već se moraju predočiti javnosti.

2.  Znanost je objektivna spoznaja svijeta – interpretacije i zaključci ne smiju biti pod utjecajem stavova, vrijednosti ili nekih drugih subjektivnih svojstava znanstvenika

3.  Znanstvena spoznaja je empirijska – temelji se na činjenicama, a ne na spekulacijama.

4.  Znanost je sustavan i kumulativan proces – u znanosti je važna nadogradnja znanja, nove pojedinačne činjenice se nikada ne promatraju same za sebe već uvijek u jednom širem korpusu znanja koje je razvijeno u okviru neke znanstvene discipline u prošlosti.

5.  Znanost je prediktivna – znanost pokušava predvidjeti na koji će se način pojave i fenomeni koje proučava zbivati u budućnosti.

Suštinu znanstvene spoznaje određuje priroda **njenog predmeta i njenih metoda**. Dok prirodne znanosti svoj predmet definiraju kao materijalni svijet tj. materijalnu prirodu, društvene znanosti svoj predmet definiraju kao rezultat ljudskih interakcija koje su se odvijale u prošlosti ili koje se odvijaju u sadašnjosti. Interakcije među ljudima rezultiraju različitim društvenim tvorbama i fenomenima koje proučavaju sociologija, ekonomika, povijesne znanosti, antropologija, komunikologija kao i ostale društvene znanosti. Primjerice, neki od predmeta suvremenih društvenih znanosti su *utjecaj medija, društvene nejednakosti, društvene vrijednosti, politički odnosi, društveni razvoj, društvena stratifikacija, geopolitički odnosi* itd. Shodno tome možemo konstatirati da je prvi preduvjet znanosti postojanje **predmeta znanstvenog istraživanja.** On se može definirati kao dio prirodnog ili društvenog svijeta koji je empirijski istraživ, tj. kao entitet o čijoj se prirodi mogu donijeti zaključci temeljem iskustvenih podataka, a koji je predmet znanstvenog interesa. Izbor predmeta istraživanja prvi je korak u provođenju znanstvenog istraživanja, a predstavlja dodjeljivanje statusa posebne važnosti nekom elementu izdvojenom iz cjeline svijeta (Afrić, 1989:17).

Drugi preduvjet znanstvenog istraživanja je korištenje **znanstvene metode**. Riječ metoda potječe od grčke riječi *methodos* koja znači *put*. To pak znači da se riječju metoda može označiti proces znanstvenog spoznavanja tj. *put ka znanstvenoj spoznaji*. U užem smislu riječi metoda označava način odnošenja znanstvenika prema predmetu znanstvenog istraživanja, tj. skup propisanih procesa ili procedura odnošenja znanosti prema predmetu znanstvenog proučavanja. Posljedično tome, metoda / metode istraživanja mogu se definirati kao racionalni empirijski postupci koje znanstvenike vode istinitim spoznajama. Pomoću njih se uspostavlja veza između misli o objektivnoj stvarnosti i same stvarnosti o kojoj se misli (Vujević, 2006:25). Također, može se konstatirati da se posredstvom znanstvene metode prilikom spoznavanja prirodnog ili društvenog svijeta nastoji osloboditi ljudske subjektivnosti i proizvoljnosti (Milas, 2009:5).

Sumirajući razlike između znanstvenog i neznanstvenog pristupa proučavanju prirodnog i društvenog svijeta, Milas izdvaja sljedeće odrednice znanstvene spoznaje:

**Tablica 1.** *Odlike znanstvenog i neznanstvenog pristupa*

|                      | **Neznanstveni pristup**           | **Znanstveni pristup** |
|----------------------|------------------------------------|------------------------|
| **Opći pristup**     | Intuitivan, zdravorazumski         | Empirijski             |
| **Opažanje**         | Prigodno, nesustavno, bez kontrole | Sustavno, kontrolirano |
| **Izvještavanje**    | Subjektivno                        | Objektivno             |
| **Definicije pojmova** | Nejasne, dvosmislene             | Jasne, operacionalne   |
| **Instrumenti**      | Netočni, neprecizni                | Točni, precizni        |
| **Mjerenje**         | Nevaljano i nepouzdano             | Valjano i pouzdano     |
| **Pretpostavke**     | Neprovjerljive                     | Provjerljive           |
| **Zaključci**        | Subjektivni, osobni, nadilaze objektivne podatke | Utemeljeni na podacima |
| **Stav**             | Nekritičan                         | Kritički, skeptičan    |

Izvor: Milas (2009: 11)

Shodno svemu navedenom znanost se može definirati kao sustavni i kontrolirani postupak spoznaje prirodnog ili društvenog svijeta posredstvom provjerljivih empirijskih činjenica koje se prikupljaju u kontroliranim uvjetima posredstvom valjanih i pouzdanih mjernih instrumenta. Drugim riječima, znanost možemo odrediti kao onu vrstu spoznaje svijeta koju obilježava *empričnost, objektivnost, racionalnost i provjerljivost*


## Ciljevi znanstvene spoznaje

U pozadini razvoja znanosti leži veliki broj razloga. Kao prvo, možemo reći da znanost vrlo vjerojatno nastaje kao posljedica urođenih čovjekovih interesa za svijet oko sebe. Oduvijek su ljudi imali potrebu razumjeti prirodne pojave i zbivanja u okolini u kojoj žive. Željeli su objasniti i razumjeti prirodne pojave poput kiše, vjetra, smjenjivanja godišnjih doba, bolesti i slično. Zasigurno je taj, gotovo instinktivni poriv za objašnjenjem svijeta, bio jedan od ključnih pokretača nastanka prvo filozofije, a zatim i znanosti. Drugo, razvoj znanosti posljedica je i civilizacijskih razloga – potrebe prilagođavanja prirodnog okoliša čovjeku, posljedica potrebe kultivacije prirode. Treće, znanost se razvija i u suodnosu s razvojem tehnologije. Prema Joelu Mokyru, ekonomskom povjesničaru, suvremena znanost modernog doba u 17., 18. i 19. stoljeću razvija se uslijed sve veće potrebe za razvojem tzv. „korisnog" znanja, tj. tehnoloških inovacija. Riječ je o tome da razvoj novih tehnologija zahtjeva bolje razumijevanje fizikalnih zakona i kemijskih procesa. (Mokyr, 2007.). I naposljetku, društvene znanosti razvijaju se uslijed društvenih promjena potiče proces modernizacije društava zapadnog civilizacijskog kruga (18. – 20. stoljeće), a koje rezultiraju pojavom novih društvenih fenomena kao što su urbanizacija, industrijalizacija, promjena društvene strukture, pojava novih društvenih klasa i izvorišta društvenih sukoba, kao i uslijed potrebe za novim modalitetima organizacije društvenog života

Mogli bismo reći da navedeni razlozi nastanka znanosti određuju i ciljeve znanstvene spoznaje. Milas (2009:17) navodi četiri temeljna cilja znanosti:

1.  **Opisivanje:** znanost želi opisati prirodne i društvene fenomene i procese. Primarno, to podrazumijeva opis njihovih svojstava, obilježja te razvoj klasifikacija i tipologija pojava. Primjerice, kada komunikolozi proučavaju navike u konzumaciji medija onda ih opisuju s obzirom na broj ljudi koji konzumira pojedini medij, npr. web portal ili televizijski program. Ili opisuju fenomen konzumacije medija s obzirom na njegova pojedina obilježja. Primjerice, 30% ljudi svaki dan čita informativne web portale, od toga njih 60% to čini preko mobilnog uređaja.

2.  **Predviđanje:** znanstvene spoznaje usmjerene su i na predviđanje događaja u budućnosti. Znanost to čini spoznajom prirodnih ili društvenih zakona. Budući da otkrivanje zakona o tome kako se neke stvari događaju predstavlja otkrivanje „ponavljajućih pravilnosti", znanstvenici temeljem svojih spoznaja mogu predvidjeti buduća događanja. Najjednostavniji primjer znanstvenog predviđanja je vremenska prognoza. Slično kao i prirodni i društveni znanstvenici predviđaju kako će se odvijati brojne društvene pojave. Primjerice, ekonomisti predviđaju kretanje bruto društvenog proizvoda, sociolozi predviđaju dinamiku društvenih nejednakosti, komunikolozi predviđaju trendove u konzumaciji i navikama konzumiranja medijskih sadržaja.

3.  **Razumijevanje**: spoznaja ponavljajućih pravilnosti podrazumijeva znanje o kauzalnosti ili povezanosti između pojava. Shodno tome, poznavanje kauzalnosti (odnosa uzroka i posljedice) podrazumijeva i razumijevanje načina na koji se odvijaju određene pojave. Primjerice, ekonomisti traže veze između kretanja zaposlenosti i rasta ili pada bruto društvenog proizvoda. Ukoliko pronađu vezu mogu konstatirati da su razumjeli pojavu. Isto je i slučaju kada sociolozi pronađu vezu između obrazovanja roditelja i školskog uspjeha djece. U tom slučaju mogu konstatirati da su razumjeli način na koji se u društvu reproducira „kulturni kapital" (obrazovanje).

4.  **Kontrola**: jedan od krajnjih ciljeva znanosti je mogućnost utjecaja na pojave koje se istražuju. Znanstvena istraživanja trebala bi rezultirati spoznajama koje će poboljšati prirodne i društvene uvjete života ljudi. To se postiže razvojem novih tehnologija.

## Znanost i pseudoznanost

Suvremena filozofija znanosti, između ostalog, bavi se i kriterijima posredstvom kojih se znanost razgraničava od drugih načina spoznaje svijeta. Primjerice, društveni svijet se može spoznavati i osobnim uvidima, intuicijom, zdravorazumskim razmišljanjem, filozofskim promišljanjem ili posredstvom umjetnosti. Svaki od ovih načina spoznaje svijeta ima neka svoja pravila, postavlja svoja specifična pitanja, određuje svoja načela spoznaje. Međutim, ona se značajno razlikuju od načela znanstvene spoznaje. Također, izuzev razlikovanja znanosti od ostalih način spoznaje, filozofija znanosti puno je pažnje pridala razlikovanju znanosti od tzv. pseudoznanosti. To razlikovanje posebno je važno danas, kada živimo u vremenu u kojem je sveprisutnost na društvenim mrežama činjenica, i u kojem je prisutna neograničena mogućnost da se njima posreduju gotovo svi zamislivi idejni koncepti, uvjerenja i stavovi (primjerice teorija o zemlji kao ravnoj ploči). Drugim riječima, zahvaljujući Internetu i društvenim mrežama zadnjih godina raste broj različitih pseudoznanstvenih koncepata koji se brzo šire te su stoga sve prisutniji u javnosti.

**Pseudoznanost** se može definirati kao aktivnost koja oponaša znanost, pokušaj da se „kopira" znanstvena procedura kao i znanstveno rezoniranje bez strogog pridržavanja načela znanstvenog djelovanja. Dakle, pseudoznanost krivotvori znanstvenu proceduru na način da ju oponaša ili lažira. Najpoznatiji filozofi koji su se bavili problematikom razgraničenja znanosti i pseudoznanosti su Imre Lakatos i Karl Popper.

U svom djelu *Logika znanstvenog otkrića* Popper (1973 [1959]) kao kriterij razgraničenja znanosti od pseudoznanosti uvodi kriterij **opovrgljivosti**. Popper iznosi tezu da znanstvene teorije moraju imati svojstvo opovrgljivosti. Ukoliko se neka teorija ne može opovrgnuti empirijskim dokazima, tada se prema Popperu o njoj ne može govoriti kao o znanstvenoj teoriji. Prema Popperu, primjer pseudoznanstvenih teorija su marksizam i psihoanaliza. To su teorije s velikom potencijalom za „imuniziranje", tj. otvaraju prostor da se u teoriju stalno uvode nove teorijske propozicije što onemogućuje njihovo opovrgavanje (Popper, 2004). Primjerice, Popper navodi da prema Marxu revolucionarne promjene započinju na način da se prvo mijenjaju sredstava za proizvodnju, zatim društveni uvjeti proizvodnje, pa politička moć i na kraju ideološka uvjerenja. Međutim ruskom socijalističkom revolucijom 1918. prvo se promijenila politička moć, a tek zatim je ideologija počela mijenjati društvene uvjete i sredstva proizvodnje. Dakle, stvari su se dešavale suprotno Marxovoj teoriji. Reinterpretacija Marxove teorije revolucije od strane njegovih sljedbenika, a s ciljem izbjegavanja njene opovrgljivosti, imunizirala ju je od daljnjih napada transformirajući je u vulgarno-marksističku teoriju po kojoj ekonomski motivi i klasna borba prožimaju društveni život (Popper, 2004:55-56). Drugim riječima, Marxovi nastavljači nisu prihvaćali empirijsku neutemeljenost njegove vizije društvenog razvoja, već su kontinuirano smišljali nova objašnjenja kojima su opravdavali tj. imunizirali neuspjehe Marxovih predviđanja. Također, Popper kao opovrgljivu nije smatrao niti psihoanalitičku teoriju Sigmunda Freuda. On ju opisuje kao teoriju „kompatibilnu s mnogo svjetova". Primjerice, prema psihoanalitičkoj teoriji problemi u ponašanju buntovnog kao i anksioznog adolescenta mogu se objasniti Edipovim kompleksom (O'Hear, 2007: 53). Budući da se teorijske propozicije Freudeove teorije mogu koristiti u različitim slučajevima, a nisu provjerljive, one nisu niti opovrgljive. Posljedično tome, Freudovu teoriju, kao i Marxovu, Popper nije smatrao znanstvenim teorijama.

Upravo u pokušaju kontinuiranog opovrgavanja postojećih teorija Popper vidi osnovni smisao znanstvenog djelovanja. Stoga se prema njegovom konceptu i znanstveni napredak može promatrati iz perspektive kontinuiranih pokušaja opovrgavanja „starih" teorija. Posljedica toga je razvoj znanosti. Naime, pokušavajući opovrgavati teorije znanstvenici zapravo omogućuju njihovu evoluciju budući da se na taj način stare teorije dorađuju, tj. stare teorijske propozicije modificiraju se na način da se usklađuju s novim empirijskim evidencijama. Dakle, Popper drži da je pokušaj opovrgavanja znanstvenih teorija uzrok evolucije u znanosti, tj. uzrok znanstvenog razvoja.

## Razvoj znanosti prema Thomasu Kuhnu

Nešto drugačije promišljanje o razvoju znanosti artikulirao je Thomas Kuhn. Do izlaska njegove knjige *Struktura znanstvenih revolucija* (1999 [1962]) bilo je uobičajeno viđenje znanstvenog rada kao kumulativnog procesa. No, Kuhn iznosi ideju da se znanost ne razvija kumulacijom već revolucijom pristupa. Smatra da se razvoj znanosti može promatrati kao proces smjenjivanja različitih znanstvenih paradigmi. Pojam znanstvene paradigme može se razumjeti kao sklop znanja i uvjerenja, teorija i metoda u koje znanstvenici vjeruju, tj. koje smatraju plodonosnim u pogledu rješavanja određenih znanstvenih zagonetki. Konkretno, Kuhn navodi da paradigma s *jedne strane, označava čitavu konstelaciju uvjerenja, vrijednosti i tehnika itd., koje dijele članovi jedne određene zajednice, a s druge strane označava jednu vrstu elemenata u toj konstelaciju, ona konkretna rješenja zagonetki koja, upotrijebljena kao modeli ili kao primjeri, mogu zamijeniti eksplicitna pravila kao temelj za rješavanje ostalih zagonetki normalne znanosti* (Kuhn, 1999: 184). Dakle, paradigma predstavlja uvriježeni način rješavanja znanstvenih zagonetki u određenoj epohi, način na koji se postavljaju znanstvena pitanja kao i način na koji se na njih odgovara. Prema Kuhnu, periodi znanstvenog razvoja u kojima prihvaćene teorije i metode mogu uspješno odgovoriti na postavljena znanstvena pitanja, periodi su, tj. razdoblja, **normalne znanosti**. U razdoblju normalne znanosti teorije i empirijska istraživanja učinkovito rješavaju znanstvene zagonetke. Međutim, kada nove spoznaje, nove činjenice koje se akumuliraju znanstvenim istraživanjima počinju dovoditi u pitanje način na koji prihvaćene teorije objašnjavaju prirodu svijeta, postojeća paradigma postaje spoznajno neučinkovita, tj. unutar nje pojavljuju se aberacije – paradigma više nije u mogućnosti objasniti prirodu novih empirijskih činjenica. Takvo razdoblje Kuhn naziva razdobljima **znanstvene krize.** Kriza se razrješava **znanstvenom revolucijom**. Ona podrazumijeva promjenu paradigme. To znači da se mijenja uobičajeni način znanstvenog proučavanja, mijenjaju se teorije koje objašnjavaju prirodu svijeta kao i metode kojima se on proučava. Pojavljuju se teorije koje bolje objašnjavaju nove činjenice ili objašnjavaju više važnijih činjenica – oko njih **nastaje nova paradigma**. Dakle, rezultat znanstvene revolucije je promjena znanstvene paradigme. Nova paradigma dolazi na mjesto stare; pojavljuju se nove teorije koje bolje objašnjavaju zagonetke o prirodi svijeta. Postoje različiti primjeri koji omogućuju da se razvoj pojedinih znanosti objasni Kuhnovim konceptom. Primjerice, zamjena tzv. *mijazmatskog načela* u objašnjenju nastanka bolesti (ustajali zrak kao faktor nastanka bolesti) tzv. germinativnom teorijom (mikroorganizmi kao uzorci nastanka bolesti) jedan je od primjera koji je sukladan ideji promjene znanstvene paradigme. Slično je i s promjenom geocentričnog shvaćanja svemira s heliocentričnim. Potrebno je napomenuti da je Kuhnov koncept primjereniji za analizu razvoja prirodnih znanosti. Naime, za razliku od prirodnih znanosti, društvene znanosti u mnogo većoj mjeri obilježava svojstvo „multiparadigmatičnosti", tj. mogućnost paralelnog, istovremenog postojanja većeg broja paradigmi u okviru jedne znanosti. Prema američkom sociologu Georgu Ritzeru, multiparadigmatičnost označava koegzistenciju više temeljnih teorijskih perspektiva unutar discipline, koje nerijetko nemaju zajednički epistemološki okvir niti teže integraciji. Ta raznolikost, kako je sugerirano, prikazana je kao bogatstvo discipline, nasuprot jedinstvenosti paradigmi karakterističnoj za prirodne znanosti. (Brezovec, 2025). Primjerice iz jednog šire perspektive Lazarsfeldova teorija *dvostupanjskog djelovanja* masovne komunikacije kao i *agenda-setting* teorija mogu se razumjeti kao dva paradigmatska teorijska okvira kojima se objašnjava djelovanje medija masovne komunikacije. Oba ova paradigmatska okvira i danas je u pojedinim slučajevima moguće koristiti kao početne točke od kojih se kreće u analizu medijskog učinka. Iz perspektive oba ova teorijska okvira može se u pojedinim situacijama reći nešto o tome kako mediji utječu na ljude. Dakle, u društvenim znanostima prije postoji suživot paradigmi nego njihova stroga supstitucija.

## Sistematizacija znanosti i znanstvenih istraživanja

Postoje različiti načini sistematizacije znanosti. Npr. prema Pravilniku o znanstvenim i umjetničkim područjima, poljima i granama Nacionalnog vijeća za znanost[^2], znanstvena područja mogu se definirati na sljedeći način: *prirodne znanosti, tehničke znanosti, biomedicinske i zdravstvene znanosti, biotehničke znanosti, društvene znanosti, humanističke znanosti te interdisciplinarna područja znanosti.*

Vjerojatno je najopćenitija podjela znanosti podjela na prirodne i društveno-humanističke znanosti. Prirodne znanosti proučavaju prirodni svijet, prirodne fenomene, a društveno-humanističke svijet društvenog života; društvenih interakcija te kulturnih tvorbi. Njemački filozof Wilhelm Windelband znanosti dijeli na *nomotetske znanosti* i *idiografske znanosti*. Nomotetske znanosti su one koje nastoje otkriti ponavljajuće pravilnosti, tj. prirodne ili društvene zakone. Idiografske znanosti su one koje su usmjerene na subjektivne, pojedinačne i kao takve na neponovljive fenomene (enciklopedija.hr[^3]).

Wilhelm Dilthey razvio je koncept tzv. *duhovnih znanosti* koje je pokušao odvojiti od prirodnih znanosti (vidi Dilthey 1980). Duhovne znanosti, u koje spadaju i povijesne, znanosti su koje se bave djelovanjem čovjeka. Prema Diltheyu kod prirodnih znanosti, koje objašnjavaju prirodnu zbilju, stvari se promatraju izvana, postoji distanciranost onoga tko promatra i onoga što se promatra. Za razliku od toga, u duhovnim znanostima ne postoji distanca između subjekta i objekta promatranja što omogućuje *razumijevanje* društvenih pojava. Dakle, Dilthey duhovne znanosti određuje kao one koje se bave prirodom čovjeka i njegovog djelovanja.

Znanosti se mogu u jednom užem smislu podijeliti i s obzirom na to koja je krajnja svrha znanstvenih istraživanja. Ukoliko je primarna svrha znanstvenog istraživanja izgradnja znanstvenih teorija, tj. doprinos izgradnji znanja unutar nekog znanstvenog područja ili izgradnja tzv. *propozicijskog znanja* (Mokyr, 2007:[^4]), tada govorimo o akademskim ili fundamentalnim znanostima, tj. fundamentalnim znanstvenim istraživanjima. U slučaju ove vrste znanstvenih istraživanja spoznaje do kojih se dolazi nužno ne moraju biti praktično primjenjive. Ukoliko je riječ o istraživanjima čiji je cilj spoznaja zbog neke praktične primjene – rješavanje nekog konkretnog problema, razvoja tehnologije, unapređenja uvjeta društvenog života i sl, tj. ukoliko je cilj znanstvenog istraživanja izgradnja tzv. *instrumentalnog znanja* – tada je riječ o primijenjenim znanostima ili primijenjenim znanstvenim istraživanjima. Primjerice, fundamentalna znanstvena istraživanja u okviru komunikologije bave se testiranjem pojedinih teorijskih propozicija *agenda setting teorije*, nadopunjavanjem teorijskog koncepta *framinga* ili provjerom pojedinih postavki Lazarsfeldove *teorije dvostupnjevite komunikacije*. Nasuprot toga, primijenjena komunikološka istraživanja provode mediji kako bi utvrdili brojnosti i strukturu svoje publike. Također, ovakva istraživanja provode i agencije za tržišne komunikacije i istraživanje javnog mnijenja prilikom testiranja učinkovitosti provedenih komunikacijskih kampanja.

Znanstvena istraživanja možemo podijeliti i s obzirom na njihove tipične ciljeve, a shodno tome i na njihov krajnji spoznajni domet. U tom kontekstu možemo govoriti o eksplorativnim, deskriptivnim i kazualnim istraživanjima. Eksplorativna istraživanja nam služe da steknemo prvi uvid u temu ili istraživački problem. Obično se koriste kada je predmet istraživanja slabo istražen i poznat, a istraživač nedovoljno familijariziran s njime. Svrha ovakvih istraživanja je uglavnom razumijevanje problematike, identificiranje relevantnih pitanja i generiranje istraživačkih hipoteza. Ova vrsta istraživanja često se koristi u početnim fazama znanstvenog procesa, kada postoji potreba za orijentacijom u složenoj i nejasnoj situaciji. U društvenim znanostima vrlo često se provode posredstvom kvalitativnih metoda istraživanja, poput dubinskih intervjua ili fokus grupa . Na primjer, ako istražujemo zašto mladi sve manje koriste određenu društvenu mrežu, a o tome još nema dovoljno podataka, primijeniti ćemo eksplorativni pristup kako bismo prikupili preliminarne spoznaje i generirali li hipoteze.

Deskriptivna istraživanja, provode se kad istraživački imaju osnovne uvide u obilježje znanstvene problematike koja se istražuje, no žele doći do novih spoznaja – tj. žele opisati određene pojave i njihova obilježja. Ova istraživanja obično odgovaraju na pitanja poput "što", "tko", "gdje", na koji način, "kada". U društvenim znanostima deskriptivna istraživanja vrlo često se provode metodom ankete. Na primjer, ako želimo spoznati koliko često studenti koriste digitalne alate tijekom studija, koliko vremena provode na internetu ili koje društvene mreže koriste najviše koriste, koristiti ćemo metodu ankete. Dakle, deskriptivna istraživanja „opisuju obilježja pojava", ili obilježja relacija između varijabli koje čine pojavu (npr. utvrđuje se intenzitet korelacije ili se testira statistička značajnost razlika prikupljenih na uzorku) ali posredstvom njih nije moguće utvrditi kauzalne veze, tj. uzročno-posljedične odnose između varijabli.

Za tu svrhu koriste se kauzalna istraživanja. Glavno pitanje koje ovo istraživanje postavlja jest: "Uzrokuje li pojava X pojavu Y?" Za razliku od deskriptivnog istraživanja, koje opisuje pojave, utvrđuje kvantitativne manifestacije pojava ili eventualno utvrđuje snagu povezanosti između varijabli, kauzalna istraživanja smjeraju objasniti uzročno-posljedične odnose između pojava. Najčešće se provode metodom eksperimenta na način da istraživač aktivno manipulira jednom nezavisnom varijablom (ili grupom varijabli) kako bi proučio njihov učinak na tzv. zavisnu varijablu.

Kao što smo napomenuli, od prvih dana svog utemeljenja, komunikologija se razvijala kao primijenjena, tj. praktična, a zatim kao fundamentalna znanstvena disciplina. Važan razlog njenog nastanka kao znanstvene discipline upravo je izgradnja instrumentalnog znanja, znanja „potrebnog za rješavanje konkretnih problema u gospodarskoj, vojnoj i političkoj uporabi medija za reklamu i propagandu" (Kunczik i Zipfel, 2006:32). Paralelno s tim praktičnim razlozima, uspostavljala se i njena teorijska osnova, tj. gomilanje instrumentalnog znanja kao posljedicu je imalo razvoj i propozicijskog znanja o suodnosu medija i društva, utjecaju medija na pojedince, medijskim učincima i sl. Upravo zbog ovakvog, pomalo nespecifičnog razvojnog puta, u idućem poglavlju predočeni su istraživački problemi s kojima su se bavili utemeljitelji komunikologije i iz čijeg se rada fundirala komunikologija kao znanstvena disciplina.

## Razvoj komunikologije: utemeljitelji i prva istraživanja

Već smo spomenuli da razvoj komunikologije započinje u prvoj polovini i sredinom dvadesetog stoljeća u SAD. Bitno obilježje tog razvoja je multidisciplinarnost i policentričnost. Naime, prva komunikološka istraživanja razvijaju se u okviru različitih neovisnih istraživačkih grupa. Primjerice, Hovland-Yale istraživačka grupa koja je svoja istraživanja fokusirala na pitanja promjene stavova uslijed medijskih utjecaja proizašla je iz psihologije. Istraživačku grupu koju je predvodio Paul Lazarsfeld, a koja se bavila istraživanjem radija u Columbiji činila je većinom skupina sociologa. Istraživanja Harolda Lasswella i njegovih suradnika inklinirala su političkim znanostima i pravu. Grupu istraživača Wilbura Schramma u Illinoisu u početku su činili humanisti i novinari. Prema tome, komunikologija kakvu poznajemo danas posljedica je djelovanja na različitim znanstveno-istraživačkim područjima (McGuire, 1996: 39).

U nastavku su pobliže predstavljene aktivnosti trojice znanstvenika koji su u dali značajan doprinos razvoju komunikologije. Njihov znanstveni rad zorno zrcali spomenute interdisciplinarne korijene komunikologije, ali i upućuje na istraživačka pitanja koja su u velikoj mjeri potakla njen razvoj. Riječ je o Carlu Hovlandu, Paulu Lazarsfeldu i Kurtu Lewinu.

### Carl Iver Hovland

Carl Hovland djelovao je na sveučilištu Yale. Njegov istraživački tim u povijesti komunikologije poznat je i pod nazivom *Hovland-Yale* istraživačka grupa. Predmet Hovlandovog interesa odnosio se na to kako različiti dijelovi persuazivne komunikacije doprinose promjeni stavova (McGuire 1996). Rogers (1997) navodi da je teorijski okvir Hovladnovih istraživanja sačinjen od kombinacije biheviorizma i psihoanalitičke teorije. Hovlandova istraživačka grupa u značajnoj mjeri koristila se eksperimentalnim metodama posredstvom kojih je pokušavala pronaći povezanost između izloženosti komunikaciji i promjene stavova. Primjerice, zanimalo ga je kako na promjene stavova utječu čimbenici kao što su raspored iznošenja činjenica unutar komunikacije, karakterne osobine, efekti sporog vremenskog reagiranja (Rogres, 1997). Njegova eksperimentalna istraživanja doprinijela su brojnim spoznajama na području proučavanja metoda persuazije. Iz njih su proizašle brojne spoznaje vezane uz djelotvornost propagande kao što su važnost pouzdanosti izvora, efekt spavača, učinak jednostranih i dvostranih poruka, učinak straha na gledatelja (Rogers, 1997).

Tijekom II. Svjetskog rata (1942.) godine Hovland napušta sveučilište te prelazi u *Research Branch of the Information and Education Division u U.S. Department of War* gdje radi kao voditelj istraživačke grupe. U okviru ove institucije istražuje utjecaj propagandnih filmova poput *Why We Fight* na moral i motivaciju vojnika. U jednom širem, suštinskom smislu, ta istraživanja bavili su se općenitim utjecajem audio-vizualnih sadržaja na stavove ljudi.

Nakon rata vraća se na sveučilište. Kao njegovi najznačajniji teorijski doprinosi komunikologiji obično se ističu da vjerodostojni izvori rezultiraju intenzivnom promjenom stavova neposredno nakon komunikacijskog akta. Međutim uslijed tzv. *efekta spavača*, tijekom proteka vremena izvor se zaboravlja, tj. nema razlike između povjerenja u vjerodostojne i nevjerodostojne izvore. Dakle, utjecaj izvora je najintenzivniji nakon konzumacije poruke, a protekom vremena slabi. Jednostrane poruke rezultiraju intenzivnijom promjenom stavova u slučaju publika koje čine osobe nižeg obrazovanja, dok dvostrane poruke rezultiraju intenzivnijom promjenom stavova obrazovanije publike. Pojedinci koji su snažno privrženi grupi u manjoj mjeri biti će spremni promijeniti stavove koji u pogledu pitanja koja su oprečna grupnim normama / standardima. (Rogers, 1997).

### Paul Lazarsfeld

Po bazičnom pozivu Paul Lazarsfeld je sociolog. Njegov znanstveni rad značajno je doprinio metodama istraživanja, ne samo u komunikologiji, već i u društvenim znanostima općenito. Njegov teorijski doprinos komunikologiji najizraženiji je u razvoju teorije dvostupnjevitog toka komunikacije (*eng*. *two – step flow of communication*). Ovaj teorijski koncept apostrofira da *stvaratelji javnog mnijenja* (*eng.* *opinion leaders*) čine premosnicu između medija i publike u nekoj zajednici. Dakle, mediji masovne komunikacije prije svega utječu na stvaratelje javnog mnijenja koji zatim u procesima socijalnih interakcija s drugim članovima zajednice šire informacije. Također, rezultati Lazarsfeldovih istraživanja upućuju na to da je utjecaj komunikacijskih kampanja relativno malen. Primjerice, Lazarsfeld navodi da u slučaju predizbornih kampanja mediji uglavnom pojačavaju već oformljene stavove, a ne mijenjaju biračko opredjeljenje[^5].

Lazarsfeld je porijeklom iz Austrije gdje se već kao mladi znanstvenik počinje baviti empirijskim medijskim istraživanjima. Prva poznatija Lazarsfeldova studija (1933.) bila je ona o nezaposlenosti u Marienthalu, mjestašcu nedaleko od Beča. U ovom projektu, koji ima mnoga obilježja akcijskog istraživanja, za svoj metodološki pristup Lazarsfeld je koristio naziv sociografija. Nakon emigriranja u SAD, radi na Sveučilištu Columbija gdje je osnovao i vodio Bureau of Applied Social Research. Također, Lazarsfeld se bavio i komercijalnim, tržišnim istraživanjima, primjerice istraživanjima ponašanja potrošača. Upravo u kontekstu njegovih brojnih istraživačkih interesa i brojnih istraživačkih projekata koje je provodio treba promatrati i njegove napore u razvoju kvantitativnih metoda istraživanja. Naime, on nije bio samo praktičar, već i značajan metodski inovator. Primjerice, jedan je od pionira u mehaničkog / elektroničkog mjerenja stavova. Osmislio je tzv. *Program-Analyzer* kojim je testirao stavove o radijskom sadržaju[^6]. Rogers (1997) navodi da su dva značajna Lazarsfeldova metodološka doprinosa koji su potekli iz projekata radijskih istraživanja bili upravo Program Analyzer te fokus grupe (Rogers, 1997). Njegov je doprinos značajan i u pogledu promocije istraživanja na tzv. panel uzorcima. Panel uzorci sačinjeni su od osoba koje sudjeluju u dva ili više valova istraživanja[^7]. Ovakav uzorak koristio je u istraživanju *People's Choice* budući da je želio utvrditi da li je došlo do promjene političkog opredjeljenja nakon što su sudionici istraživanja bili izloženi predizbornoj kampanji (Rogers, 1997)[^8]. Također, Lazarsfeldovu značajnu metodološku inovaciju predstavlja *teorija o latentnoj strukturi*. Njome se inaugurira ideja postojanja latentnih dimenzija kojima se mogu objasniti povezanosti između različitih manifesnih indikatora mjerenih pojava. Lazarsfeld ističe da pojedini socijalni fenomeni predstavljaju kompleksne entitete koji nisu neposredno dostupni našoj zamjedbi. Da oni ipak postoje i djeluju zaključujemo posredno, na temelju nekih vanjskih manifestacija moje možemo opaziti i eventualno mjeriti. Te vanjske pokazatelje nazivamo indikatorima socijalnih fenomena, a samu pojavu latentnim obilježjem (Halmi, 1999:21-22). Naposljetku, Lazarsfeld je jedan od prvih društvenih znanstvenika koji je promovirao metodski pristup kojeg danas nazivamo *mješovita metodologija*. Surađujući sa sociologom Robertom K. Mertonom prvi je počeo kombinirati upotrebu kvantitativnih metoda istraživanja (npr. anketa) i kvalitativnih metoda istraživanja – dubinskih intervjua ili fokus grupa. Bio je izraziti zagovornik metodske triangualcije; korištenja većeg broja različitih metoda u okviru jednog istraživačkog projekta. Smatrao je da se društvene pojave trebaju istraživati posredstvom različitih metoda istraživanja.

Cjelokupna profesionalna karijera i akademski rad Paula Lazarsfelda bio je posvećen samo jednom jedinom cilju: mjerenju društva. Paul Lazarsfeld želio je izmjeriti društvo na način kao što prirodoslovci mjere prirodu ili psiholozi psihičke procese! Mjerio je gotovo sve što je u društvu mogao učiniti mjerljivim, bilo da se radi o odnosu društva i ekonomije, o potrošačkim navikama ljudi, o odnosu društva i medija masovne komunikacije kao i medijskim utjecajima ili o političkom ponašanju. U tu svrhu razrađivao je metode istraživanja, konstruirano mjerne instrumente, osmišljavao tehnike obrade podataka tj. činio sve što je mogao kako bi društvo prestalo biti isključivo objekt mišljenja i postalo objekt mjerenja. Stoga nije riječ samo o jednom od najvećih metodoloških inovatora u povijesti društvenih znanosti već je i riječ o znanstveniku koji ih je snažno usmjerio prema onoj formi društveno-znanstvenog bavljenja koja i danas dominira, a koju francuski sociolog Michel Lallement u svom dijelu Povijest socioloških ideja naziva *instrumentalni pozitivizam*. I pola stoljeća nakon njegove smrti zasade Lazarsfeldovog rada snažno utječu na razmišljanja, ne samo o tome kako istraživati, već i kako na temelju empirijskih podataka valjano zaključivati o društvenom svijetu

### Wilbur Schramm

Obrazovan je u području političkih znanosti i povijesti, a na počektu karijere radio je kao novinar. Nakon izbijanja Drugog svjetskog rata, Schramm je dvije godine služio kao ravnatelj obrazovanja u Uredu za činjenice i brojke US vlade, a zatim u Uredu za ratne informacije. Schrammovo ratno istraživanje, koje se ticalo propagande, pridonijelo je produbljivanju njegova interesa za korištenje masovne komunikacije kao alata za utjecaj na javno mnijenje. Godine 1943. Schramm se vratio na Sveučilište u Iowi, a 1947 se preselio na Sveučilište Illinois 1947, gdje je osnovao Institut za istraživanje komunikacija i bio njegov direktor. 1955., osniva Institut za komunikacije na Sveučilištu Stanford (Brtitanica.com).

Jedan od njegovih ključnih doprinosa je razumjevanije kako informacije putuju kroz različite kanale i kako se razmjenjuju među ljudima. Ovaj model prikazuje komunikaciju kao proces u kojem je bitno da postoji "pošiljalac", "poruka", "prijemnik" i "povratna veza". Schramm je smatrao da je komunikacija uspešna samo ako postoji zajednički kontekst između pošiljaoca i prijemnika, odnosno zajednička kultura ili iskustva.

<https://www.britannica.com/biography/Wilbur-Schramm>

### Harold Lasswell

Politolog Harold Lasswell doktorirao je 1926. na temu političke propagande u vrijeme rata. Ovom temom se bavio i tijekom II Svjetskog rata koristeći analizu sadržaja kako bi proučavao propagandu saveznika i sila osovine (Rogers, 1997). Uz Hovlanda, bio je jedan od začetnika empirijskih istraživanja propagandnih učinaka kao i začetnik korištenja kvantitativnih metoda istraživanja u istraživanjima komunikacijskih učinaka. Jedan je od prvih istraživača koji je intenzivno koristio metodu analize sadržaja, primarno u svrhu analize ratne propagande.

Nakon II. Svjetskog rata Lasswell se uključuje u tzv. Hooverove studije. Metodom analize sadržaja, zajedno sa suradnicima, obradio je 20.000 editorijala u najprestižnijim novinama pet nacija. Projekt je trajao od 1949. do 1953. godine, a s ciljem proučavanja političkih i socijalnih promjena koja se dogodile od 1890. do 1950. Analiziranje velike količine empirijskih podataka u okviru ovog projekta utjecao je na daljnji razvoj kvantitativne analize sadržaja (Rogers, 1997).

Proučavanju komunikacije Harold Laswell pristupao je intedisciplinarno. Na sveučilištu u Berlinu proučavao je psihoanalizu Sigmunda Freuda i bio je prvi koji ju je spojio sa društvenim znanostima u Americi. Načela Freudeove psihoanalize koristio je kao temelj analize djelovanja političkih vođa. Vjerovao je kako uz pomoć psihoanalize može objasniti zašto su neki političari radikali, a neki konzervativci. Jedan od najvećih doprinosa komunikologiji njegov je model komunikacije kojim objašnjava glavna područja istraživanja komunikologije, tzv. Lasswellova formula: *Who says what in which chanell to whom with what effect* (Kunczik i Zipfel, 2006:5). Laswellova formula predstavlja jedno od bazičnih određenja komunikologije budući da apostrofira glavne aktera komunikacijskog procesa: *aktere koji proizvode i diseminiraju medijske sadržaja (tko?)*, *medijski sadržaj – što se govori (što?)*, *prijenosnike poruke – medije (kojim kanalima?), primatelje poruke – medijsku publiku (kome?) te medijske efekte – direktne i indirektne učinke medijske komunikacije.*

[^1]: https://enciklopedija.hr/natuknica.aspx?ID=32686

[^2]: https://narodne-novine.nn.hr/clanci/sluzbeni/2009_09_118_2929.html

[^3]: https://enciklopedija.hr/natuknica.aspx?ID=26aborativna7

[^4]: https://www.journals.uchicago.edu/doi/10.1086/511993

[^5]: Vidi osvrt na tu studiju u Kunznik i Zifpel (2006: 102–103)

[^6]: Vidi sliku program analizera na: https://en.wikipedia.org/wiki/Program_Analyzer

[^7]: O metodološkim svojstvima panel istraživanja će se više govoriti u poglavlju o anketi.

[^8]: Vidi osvrt na tu studiju u Kunznik i Zifpel (2006: 102–103)
