# Ciljevi znanstvene spoznaje

U pozadini razvoja znanosti leži veliki broj razloga. Kao prvo, znanost nastaje kao posljedica
urođenih čovjekovih interesa za svijet oko sebe. Oduvijek su ljudi imali potrebu razumjeti
prirodne pojave i zbivanja u okolini u kojoj žive. Zasigurno je taj, gotovo instinktivni poriv za
objašnjenjem svijeta, bio jedan od ključnih pokretača nastanka prvo filozofije, a zatim i
znanosti. Drugo, razvoj znanosti posljedica je i civilizacijskih razloga: potrebe prilagođavanja
prirodnog okoliša čovjeku, posljedica potrebe kultivacije prirode. Treće, znanost se razvija i
zbog potrebe razvoja tehnologije. Prema Joelu Mokyru, ekonomskom povjesničaru,
suvremena znanost modernog doba u 17., 18. i 19. stoljeću u velikoj mjeri razvija se uslijed sve
veće potrebe za razvojem tzv. „korisnog znanja“, tj. tehnoloških rješenja koja će biti iskoristiva
u svakodnevnom životu. Kako bi se došlo do njih, bilo je potrebno spoznati i razumjeti fizikalne
zakone i kemijske proces (Mokyr, 2007.). I naposljetku, društvene znanosti razvijaju se uslijed
društvenih promjena koje potiče proces modernizacije društava zapadnog civilizacijskog kruga
(18. – 20. stoljeće), a koje rezultiraju pojavom novih društvenih fenomena kao što su
urbanizacija, industrijalizacija, promjena društvene strukture, pojava novih društvenih klasa i
izvorišta društvenih sukoba, kao i uslijed potrebe za novim modalitetima organizacije
društvenog života.
Navedeni razlozi nastanka znanosti u velikoj mjeri određuju i ciljeve znanstvene spoznaje.
Milas (2009:17) navodi četiri temeljna cilja znanosti:
1. Opisivanje: znanost želi opisati prirodne i društvene fenomene i procese. Prije svega to
podrazumijeva opis njihovih svojstava te razvoj klasifikacija i tipologija pojava. Primjerice, kada
komunikolozi proučavaju navike u konzumaciji medija onda ih opisuju s obzirom na broj ljudi
koji konzumira pojedini medij, npr. web portal ili televizijski program. Ili pak opisuju fenomen
konzumacije medija s obzirom na njegova pojedina obilježja: 30% ljudi svaki dan čita
informativne web portale, od toga njih 60% to čini preko mobilnog uređaja.
2. Predviđanje: znanstvene spoznaje usmjerene su i na predviđanje događaja u budućnosti.
Znanost to čini spoznajom prirodnih ili društvenih zakona. Budući da otkrivanje zakona o tome
kako se neke stvari događaju predstavlja otkrivanje „ponavljajućih pravilnosti“, znanstvenici
temeljem svojih spoznaja, s određenom vjerojatnosti mogu predvidjeti buduća događanja.
Najjednostavniji primjer znanstvenog predviđanja je vremenska prognoza. Slično kao i

znanstvenici koji proučavaju prirodne pojave i društveni znanstvenici predviđaju kako će se
odvijati brojne društvene pojave. Primjerice, ekonomisti predviđaju kretanje nezaposlenosti,
sociolozi predviđaju dinamiku društvenih nejednakosti, komunikolozi predviđaju trendove u
konzumaciji i navikama konzumiranja medijskih sadržaja.
3. Razumijevanje: spoznaja ponavljajućih pravilnosti podrazumijeva znanje o kauzalnosti ili
povezanosti između pojava. Shodno tome, poznavanje kauzalnosti (odnosa uzroka i
posljedice) podrazumijeva i razumijevanje načina na koji se odvijaju određene pojave.
Primjerice, ekonomisti traže veze između kretanja zaposlenosti i rasta ili pada bruto
društvenog proizvoda. Ukoliko pronađu vezu mogu konstatirati da su razumjeli pojavu. Isto je
i slučaju kada sociolozi pronađu vezu između obrazovanja roditelja i školskog uspjeha djece. U
tom slučaju mogu konstatirati da su razumjeli način na koji se u društvu reproducira „kulturni
kapital“ (obrazovanje).
4. Kontrola: jedan od krajnjih ciljeva znanosti je mogućnost utjecaja na pojave koje se
istražuju. Znanstvena istraživanja trebala bi rezultirati spoznajama koje će poboljšati prirodne
i društvene uvjete života ljudi. To se postiže razvojem novih tehnologija.
