---
title: "Epistemološke osnove istraživanja"
author: ""
lang: hr
format:
  html:
    toc: true
    toc-depth: 3
    number-sections: true
    number-offset: [3]
  pdf:
    toc: true
    toc-depth: 3
    number-sections: true
    number-offset: [3]
    latex-engine: xelatex
---

Društvene znanosti, pa tako i komunikologija, su multimetodske. To znači da su u okviru njih razvijene brojne metode, istraživačke tehnike i metodski postupci kojima se znanstvenici koriste prilikom istraživanja društvenih fenomena. Na najopćenitijoj razini, spomenuto metodsko bogatstvo može se klasificirati u dvije kategorije: kvantitativne i kvalitativne metode istraživanja.

Jednostavno rečeno, kvantitativne metodama pokušavaju se objasniti kvantitativne relacije u pojavama koje se istražuju (npr. broj ljudi koji konzumira određeni medij), dok se kvantitativnim metodama pokušavaju interpretirati motivi socijalnih aktera (npr. što ih potiče da konzumiraju određeni medij) ili značenja koji oni daju svojim akcijama ili pojedinim fenomenima u socijalnom svijetu[^9].

Bez obzira na razlike koje među njima postoje, istraživači koji koriste bilo kvantitativne, bilo kvalitativne metode, polaze od toga da znanstveno spoznavanje društvenih fenomena mora biti utemeljeno na podacima iz stvarnog svijeta (Maravsti, 2004). Dakle, ove dvije metodske grupe nastoje posredstvom empirijskih podataka opisati, objasniti, razumjeti i interpretirati kompleksnu socijalnu stvarnosti. Iako se radi o dva pristupa koja su po svojem temeljnom cilju komplementarni, obilježavaju ih razlike u filozofskim korijenima i epistemološkim izvorima (Halmi, 1996).

Kvantitativne metode istraživanja svoje ishodište pronalaze primarno u empirističkoj i pozitivističkoj spoznajno-teorijskoj tradiciji. Kvalitativne metode istraživanja svoje spoznajno-teorijske korijene baštine u hermeneutičkoj tradiciji, fenomenologiji kao i općenito u interpretativnim pristupima razvijenim u okviru društvenih znanosti, npr. etnometodologiji i simboličkom interakcionizmu.

## Spoznajno-teorijske osnove kvantitativnih metoda istraživanja

Empirizam kao specifična filozofsko-gnoseološka tradicija pojavljuje se u Engleskoj u drugoj polovini 17. stoljeća. Najistaknutiji predstavnici empirizma su John Lock, Francis Bacon i David Hume. Osnovni postulat empirističke filozofije je onaj prema kojem je spoznaja moguća samo temeljem iskustva. Pozitivizam kao specifičan filozofski smjer, blizak empirizmu, nastaje u 19. stoljeću, a njegove ideje prvi je proklamirao Auguste Comte. U svom djelu Kurs pozitivne filozofije on odbacuje metafiziku kao princip spoznaje te kao i empiristi, također postulira iskustvo kao jedini izvor pozitivne spoznaje. Smatra da je spoznaja moguća samo na temelju empirijskih činjenica, a idealni način spoznavanja je onaj koji je utemeljen u okviru prirodnih znanosti. Daljnji doprinos razradi pozitivističkih i empirističkih principa početkom dvadesetog stoljeća dali su filozofi koji su zastupali načela tzv. logičkog pozitivizma. Logički pozitivisti tzv. Bečkog kruga (npr. Hahn, Neurath, Carnap)[^10] znanstveno shvaćanje svijeta prvenstveno određuju s dvije oznake, kao empirističko i pozitivističko: „postoji samo iskustvena spoznaja, koja postoji na onome neposredno danome" (Hahn, Neurath, Carnap: 2005, 29). Smatraju da znanstveno shvaćanje svijeta na poznaje nikakvu bezuvjetno valjanu spoznaju iz čistog uma, nikakve sintetičke sudove „a priori" te da znanstveno shvaćanje svijeta ne poznaje nikakve nerješive zagonetke, već da je usmjereno na rješavanje empirijskih problema (Hahn, Neurath, Carnap: 2005). Može se konstatirati da logički pozitivizam promiče načelo verifikacije koje naglašava empirističko stajalište, a metafizičke principe odbacuje kao besmislene.

U jednom širem smislu, tradicija pozitivističke filozofije promiče i ideju da fenomeni koji se opažaju na jedan direktan način utječu na naše i opažanje, tj. da postoji direktna korespondencija između stvari i njihovih reprezentacija. Zbog toga je i moguće opisati vanjski svijet i to na ispravan način (Willig: 2016:25). Prema Milasu (2009:15) pozitivizmu je svojstveno uvjerenje o postojanju spoznatljive zbilje upravljane nepromjenjivim prirodnim zakonima. Stoga se znanost, sukladno pozitivističkom učenju, treba baviti otkrivanjem zakona koji uobličuju ono što prepoznajemo pod objektivnom stvarnošću. Pozitivističko gledište shodno Milasu može se razložiti na nekoliko temeljnih načela:

1. Prirodom vlada red.
2. Priroda je spoznatljiva.
3. Znanje je nadmoćno neznanju.
4. Sve prirodne pojave imaju prirodne uzroke.
5. Ništa nije samo po sebi razumljivo.
6. Znanje se usvaja iskustvom.

Prema pozitivističkom shvaćanju, ova načela mogu se primijeniti i na društvene znanosti. Prvenstveno to se odnosi na shvaćanje da se društvo može razumjeti kao uređeni sustav u kojem vlada red. To podrazumijeva da u društvu djeluje niz zakona neovisnih od individualnog djelovanja društvenih aktera, tj. da društveni zakoni djeluju neovisno od pojedinaca. Primjerice, prema francuskom sociologu Emilu Durkheimu, sociologija se bavi proučavanjem društvenih činjenica, tj. bavi se onime što je izvanjsko pojedincu i što je nezavisno od pojedinačnog djelovanja (Durkheim, 1999). Društveni zakoni koji opisuju objektivnu, od pojedinca neovisnu društvenu stvarnost mogu se spoznati empirijskim činjenicama. Posljedično tome, kao i prirodne znanosti i društvene znanosti trebale bi biti usmjerene ka spoznaji društvenih zakona, tj. trebale bi biti usmjerene ka spoznaji kauzalnih odnosa između varijabli kojima se mogu opisati pojedine društvene pojave. Zbog toga bi se iz pozitivističke perspektive istraživački postupci društvenih znanosti trebali temeljiti na identičnim metodskim principima kao i istraživački postupci u prirodnim znanostima. To znači da usprkos razlika u predmetu istraživanja, pozitivizam promiče ideju metodološkog monizma, tj. promiče ideju o jedinstvu metoda prirodnih i društvenih znanosti (Halmi, 1999:12). Drugim riječima, pozitivistička spoznajno-teorijska tradicija sugerira da način bavljenja znanošću, način na koji se postavljaju znanstvena pitanja i daju znanstveni odgovori u slučaju društvenih i prirodnih znanosti treba biti identičan. Kao i prirodne, i društvene znanosti trebaju se usmjeriti prema traganju za kauzalnim odnosima. Kao i u prirodnim znanostima, i u društvenim znanostima istraživač „nastoji utvrditi šte se zbilo s deskriptivnim varijablama, pa zbivanja pretvara u ljestvice, mjerenja, brojeve, tabele, grafikone itd.., a matematičko statističke formalizacije sastavni su dio znanstvenog istraživanja" (Tomić-Koludrović i Leborić: 2002: 203-204). Dakle, ova spoznajno-teorijska tradicija promiče ideju da društvene znanosti svoje predmete trebaju proučavati na identičan način kao što to rade i prirodne znanosti. Upravo navedenu epistemološku postavku možemo smatrati kamenom temeljcem razvoja kvantitativnih metoda istraživanja u društvenim znanostima. Ona se može opisati i putem sljedećih obilježja:

1. Društveni svijet je neovisan od pojedinačnog djelovanja.
2. Spoznaja društvenog svijeta pretpostavlja spoznaju društvenih zakona.
3. Osjetilno / empirijsko opažanje utemeljuje pravo znanje o društvu.
4. Ideal empirijskih evidencija onaj je iz prirodnih znanosti; svojstva društvenog svijeta mogu se objasniti kvantitativnim podacima (statistička forma podataka).
5. Istraživanje započinje teorijom iz koje se izvode hipoteze koje se zatim testiraju temeljem empirijskih podataka. Testiranjem se hipoteze prihvaćaju, modificiraju ili odbacuju. Time se i sama teorija od koje se kreće u istraživanje prihvaća, nadograđuje, modificira ili odbacuje.

Posljedično ovim spoznajno-teorijskim postulatima, kao osnovna obilježja kvantitativnih metoda u društvenim znanostima možemo izdvojiti sljedeće:

: Osnovna obilježja kvantitativnih metoda istraživanja u društvenim znanostima {#tbl-kvant}

| Dimenzija | Obilježja |
|---|---|
| **Pretpostavke** | Društvene činjenice imaju objektivnu realnost. Varijable se mogu identificirati, a odnosi mjeriti. Pogled izvana. Istraživač unaprijed zna što traži. Dizajn istraživanja je zatvoren; svi aspekti istraživanja pažljivo su dizajnirani prije nego što se krene u istraživanje. |
| **Svrha** | Testiranje hipoteza. Poopćavanje. Predikcija. Kauzalna objašnjenja. |
| **Pristup** | Počinje hipotezom i teorijama. Upotreba formalnih instrumenata. Deduktivno zaključivanje. Reducira podatke na numeričke indicije. |
| **Uloga istraživača** | Odvojenost i nepristranost. Objektivna interpretacija; precizno mjerenje, objektivnost, pouzdanost. |

Izvor: Adaptirano prema Skoko-Benković (2009).

Dobar primjer komunikološkog istraživanja koje bi bilo provedeno metodom kojoj su svojstvena sva predočena obilježja kvantitativnih metoda, istraživanje je medijske pismenosti metodom ankete. Takvo istraživanje moglo bi biti provedeno na način da se u izradu mjernog instrumenta, ankete, krene od nekih od postojećih definicija medijske pismenosti. Primjerice, medijska pismenost se uobičajeno definira kao sposobnost pristupanja, analize i vrednovanja medija u različitim formama te kao kompetentna komunikacija unutar tih formi (Livingstone, 2004, Bulger, 2012). Na osnovu ove definicije mogu se razviti empirijski indikatori (pitanja u upitniku, tj. mjerne ljestvice) posredstvom kojih će se mjeriti medijska pismenost na određenoj populaciji (npr. svi punoljetni građani RH). Prilikom konstrukcije mjernog instrumenta (upitnika) pazit će se na pouzdanost i valjanost konstruiranih mjernih ljestvica. U nacrtu istraživanja biti će postavljeno nekoliko istraživačkih hipoteza koje će se testirati na osnovu prikupljenih podataka. Npr. moguće je postaviti hipotezu da razina medijske pismenosti ovisi o obrazovanju osobe. Ili, moguće je postaviti hipotezu da su osobe mlađe od 40 godina medijski pismenije od osoba starijih od 40 godina. Nakon što se na određenom znanstveno konstruiranom uzorku provede istraživanje i prikupe podaci, temeljem statističkih procedura testirat će se postavljene hipoteze te će se na osnovu rezultata statističkih testova kao objektivnih mjerila one odbaciti ili prihvatiti. Shodno tome donijeti će se i zaključci.

## Spoznajno-teorijske osnove kvalitativnih metoda istraživanja

Glavni prigovor zagovornika korištenja kvalitativnih metoda u društvenim znanostima je taj što oni smatraju da „kvantifikacija nameće određenu (lažnu) čvrstoću društvenom životu koju on ne posjeduje" (Tomić-Koludrović i Leborić, 2002:204). Zagovornici ovih metoda istraživanja drže da su društveni fenomeni uvijek socijalno konstruirani, da su posljedica društvenih interakcija, komunikacije, posredovanja značenja i interpretacija. Zbog toga ih nije niti moguće proučavati na način na koji prirodne znanosti proučavaju svoje predmete, već je potrebno koristiti drugačiji metodski pristup. Taj drugačiji metodski pristup u proučavanju društvenih pojava promoviraju tzv. kvalitativne metode istraživanja.

Kvalitativne metode mogu se definirati kao multiparadigmatski i multimetodski usmjerena istraživanja koja uključuju naturalistički i interpretativni pristup predmetu istraživanja (Halmi i Crnoja, 2003:1). To znači da istraživanja koja se provode posredstvom kvalitativnih metoda uvijek pristupaju proučavanju subjekta u njegovom povijesnom i društvenom kontekstu nastojeći razumjeti i interpretirati smisao ili značenje njegovih akcija, doživljaja, svakodnevnog iskustva.

Spomenuto određenje kvalitativnih metoda sintetizira njihova najčešće isticana obilježja. Primjerice, Marshall i Rossman (2011:3) navode da se osnovna obilježja kvalitativnih metoda istraživanja mogu svesti na sljedeće:

1. Istraživanja koja se provode posredstvom kvalitativnih metoda odvijaju se u prirodnom socijalnom okruženju;
2. oslanjaju se na višestrukost metoda koje poštuju prirodu sudionika istraživanja;
3. fokusirana su na kontekst;
4. fundamentalno su interpretativna.

Shodno tome, Marshall i Rosman navode da „kvalitativni istraživači":

1. vide socijalni svijet kao holistički i kompleksan;
2. sistematski reflektiraju korake u provođenju istraživanja;
3. ostaju senzitivni prema osobnoj biografije / društvenom identitetu sudionika istraživanja i načinu na koji oni utječe na istraživanje;
4. koriste kompleksne načine rezoniranja i zaključivanja koji su višeznačni i iterativni.

Willig (2016: 35) napominje da su „kvalitativni istraživači" obično zainteresirani za značenje, tj. zainteresirani su za to kako ljudi pridaju smisao svijetu i kako doživljavaju ono što im se događa. Dakle, kvalitativni istraživači skloni su baviti se kvalitetom i teksturom ljudskog iskustva prije nego identifikacijom uzročno-posljedičnih odnosa. Slično ističe i Marvasti (2004:7) kada kaže da istraživanja koja se provode kvalitativnim metodama pružaju detaljan opis suštine ljudskog iskustva. Sumirajući specifičnosti kvalitativnih metoda istraživanja u odnosu na kvantitativne, Tomić-Koludrović i Leborić (2002) ističu da su kvalitativne metode istraživanja koncentrirane na značenje ili na ponašanje, tj. da se osnovni cilj kvalitativnog istraživanja svodi na dokumentiranje svijeta s različitih pozicija sudionika istraživanja. Prema tome, jedno od najvažnijih obilježja kvalitativnih metoda istraživanja je „centralnost interpretacije" (Tomić-Koludrović i Leborić, 2002:209). Svrha interpretacije je „razumijevanje svijeta", razumijevanje značenja koji ljudi pridaju svojim akcijama ili razumijevanje motiva koji ih pokreću u njihovom djelovanju. Spasić (1998:9) navodi da je zastupnicima interpretativnog pristupa u društvenim znanostima važno zahvaćanje akterovog unutrašnjeg doživljaja situacije i vlastitog djelovanja. Upravo na temelju tog impulsa počinje se razvijati kvalitativna metodologija u društvenim znanostima (Spasić, 1998:9).

U jednom širem smislu, kvalitativne metode istraživanja svoje korijene baštine u hermeneutičkoj tradiciji i fenomenologiji te u pojedinim propozicijama etnometodologije i simboličkog interakcionizma.

Hermeneutika je izvorno filozofski nauk o razumijevanju i tumačenju biblijskih, pravnih, književnih i filozofskih spisa[^11]. U jednom širem smislu može se odrediti kao vještina tumačenja i razumijevanja tekstova. Kao specifična spoznajna vještina u društvene znanosti ulazi posredstvom filozofije Wilhelma Diltheya. Već smo napomenuli da on razvija koncept duhovnih znanosti kojim one znanosti koje se bave posljedicom djelovanja ljudi pokušava odijeliti od prirodnih znanosti. Prema Diltheyu, duhovne znanosti utemeljenje su u psihološkoj ili duhovnoj prirodi ljudskog djelovanja. Budući da se bave duhovnom prirodom čovjeka i njegovog djelovanja one su inherentno interpretativne. Zbog toga je i hermeneutički princip razumijevanja ono što ih prema Diltheyu razlikuje od prirodnih znanosti[^12]. Diltheyovu koncepciju prihvatio je, a zatim i dalje razradio jedan od utemeljitelja suvremene sociologije Max Weber. Njegov metodološki pristup znan je kao metodološki individualizam. Weber smatra da se sve društvene pojave mogu svesti na individualno djelovanje. Stoga je i zadatak društvenih znanosti upravo rekonstrukcija individualnog djelovanja. Rekonstruirati individualno djelovanje znači razumjeti ga, tj. razumjeti motive koji pokreću aktivnosti pojedinca (Weber, 1989). Prema tome, tradicija društvenih znanosti koja proizlazi iz hermeneutičkog pristupa kao i Weberovog metodološkog individualizma promiče ideju da su društveni događaji posljedica pojedinačnog djelovanja i kao takvi obično jednokratni i neponovljivi, da društvene znanosti proučavaju upravo pojedinačne događaje, a da bi se oni mogli razumjeti potrebno je razumjeti unutarnja stanja pojedinaca i motive koji stoje u pozadini njihovog djelovanja[^13].

Uz hermeneutičku tradiciju, važno zaleđe razvoja kvalitativnih metoda istraživanja može se pronaći i u fenomenologijskoj spoznajno-teorijskoj tradiciji. Njen utemeljitelj je njemački filozof Edmund Husserl. On je ideju fenomenologije predstavio u djelu Logička istraživanja (objavljeno 1900./1901.). Filozofija se prema Husserlu treba baviti „fenomenima", tj. onim što se pojavljuje u ljudskoj svijesti, načinom na koji se iskustvo o stvarima koje nas okružuju upisuje u našu svijest. Husserl smatra da središnje mjesto filozofske analize treba postati individualno iskustvo, tj. manifestiranje suština pojava u ljudskoj svijesti. Dakle, fenomenologija na prvo mjesto stavlja ljude, njihovo iskustvo, način na koji ljudi doživljavaju svijet oko sebe. Ova temeljna fenomenologijska pozicija inspirira jednu od suštinskih propozicija kvalitativnih metoda istraživanja, usmjerenost na iskustvo. Cilj istraživanja inspiriranog fenomenologijskim principima je „što bliže prići iskustvu pojedinaca te dobiti pristup njihovom doživljajnom svijetu" (Willig, 2013:50). Upravo u kontekstu fenomenologijske tradicije treba promatrati i činjenicu da kvalitativne metode istraživanja u jednom velikom dijelu nastoje pružiti odgovor na pitanje „kako izgleda svijet za ovog sudionika istraživanja" (Willig, 2013:50).

Glavne fenomenologijske propozicije korespondiraju i s osnovnim postavkama one teorijske tradicije u sociologiji koja se naziva etnometodologija. Ona stavlja naglasak na način na koji ljudi konstruiraju smisao svog društvenog djelovanja. Promiče istraživanja „metoda" koje članovi društva koriste u konstrukciji društvenog poretka (Abercrombie i Hill, 2008:83).

Pojedina ishodišta kvalitativnih metoda istraživanja mogu se pronaći i u teorijskoj tradiciji simboličkog interakcionizma. Ona se razvija na učenju Georga Herberta Meada o prirodi društvenih interakcija kao i na radovima sociologa Herberta Blumera. Simbolički interakcionizam postulira tezu da ljudi u međusobnim interakcijama ne reagiraju „direktno", već da se njihova reakcija zasniva na značenjima koje oni takovim akcijama pridaju. U ovom je smislu artikulirana i temeljna teorijska pretpostavka simboličkog interakcionizma, pretpostavka da društvena stvarnost onakva kakova se osjeća, spoznaje i razumijeva jest producirana društvenom simboličkom interakcijom (Afrić, 1988: 2). Upravo u navedenoj teorijskoj propoziciji simboličkog interakcionizma možemo potražiti ishodište još jednog značajnog obilježja kvalitativnih metoda istraživanja, nastojanja da se protumače različita značenja koja ljudi pridaju svojem djelovanju te značenja koje pridaju različitim društvenim procesima u kojima sudjeluju.

[^9]: Napomena o razlikovanju kvantitativnih i kvalitativnih metoda.
[^10]: Predstavnici Bečkog kruga logičkog pozitivizma.
[^11]: Hermeneutika kao filozofski nauk o razumijevanju i tumačenju tekstova.
[^12]: Diltheyov hermeneutički princip razumijevanja kao razlikovna oznaka duhovnih i prirodnih znanosti.
[^13]: Veza hermeneutičkog pristupa i Weberovog metodološkog individualizma.
