---
title: "Nacrt istraživanja"
---

Empirističko-pozitivistička spoznajna tradicija ishodište je kvantitativnih metoda istraživanja u društvenim znanostima. Stoga je i način na koji se posredstvom kvantitativnih metoda pokušava spoznati kompleksnost društvenog svijeta sličan načinu na koji to čine prirodne znanosti u spoznavanju prirodnog svijeta. Kvantitativne metode istraživanja najčešće se upotrebljavaju kada se žele spoznati kauzalne relacije u nekom društvenom fenomenu (uzroci i posljedice), kada se želi utvrditi povezanost između varijabli (korelacija), kada se žele testirati razlike između pojedinih grupa sudionika istraživanja s obzirom na njihove prosječne vrijednosti na nekoj varijabli ili kada se žele opisati različita kvantitativna svojstva društvenih pojava (rasprostranjenost, intenzitet i tsl.). Kvantitativne metode također se koriste kada se istraživanjima žele provjeriti, opovrgnuti ili nadograditi pojedine znanstvene teorije, tj. kada se u istraživanje kreće od hipoteza koje se izvode iz pojedinih teorijskih koncepata, a koje se žele testirati novim empirijskim podacima.

Dakle, kvantitativne metode društvenih istraživanja fokusirane su na mjerenje društvenih pojava / fenomena sa ciljem njihove kvantifikacije. Mjerenje se obavlja na način da se u pripremi istraživanja posredstvom procesa operacionalizacije, teorijski konstrukti definiraju kao niz mjerljivih varijabli. Varijable su promjenjiva obilježja, tj. obilježja koja mogu poprimiti različite vrijednosti. Postoji niz različitih klasifikacija varijabli među kojima je temeljna ona koja ih dijeli na:

1.  Nominalne

2.  Ordinalne

3.  Intervalne

4.  Omjerne

**Nominalne varijable** su klasifikacije kojima se različiti objekti ili obilježja raspoređuju u kvalitativno različite grupe. Primjerice nominalna varijabla je mjesto stanovanja. Dakle, brojevi u slučaju nominalnih varijabli predstavljaju samo oznake pripadanja određenoj klasi (npr. 1-grad, 2-selo)[^14].

**Ordinalne varijable** predstavljaju rangiranje nekih svojstava temeljem određenog kriterija (npr. više-manje, bolje-lošije i tsl.). Kod ordinalnih varijabli brojevi označavaju samo redoslijed ali ne i stvarni razmak među rangiranim objektima. Primjerice, ordinalne varijable su razina obrazovanja ili činovi u vojsci.

**Intervalne varijable** su numeričke varijable kod kojih, osim što postoji rangiranje između vrijednosti, postoji i ekvidistanca. Naime, razlike između bilo koje dvije susjedne vrijednosti su precizne i konstantne. Primjer je temperatura izražena u stupnjevima Celzijusa. Možemo reći da je razlika između 10 i 20 stupnjeva ista kao i razlika između 30 i 40 stupnjeva Celzijusa. Bitno obilježje ovih varijabli je da je nula arbitrarno određena. Stoga u slučaju intervalnih varijabli nula ne znači nepostojanje pojave[^15]. Intervalne varijable dopuštaju numeričke operacije (npr. računanje prosječen vrijednosti, provođenje testova statističke značajnosti). Primjer intervalnih varijabli: temperatura u stupnjevima Celzijusa, broj ostvarenih bodova na testu.

**Omjerne varijable** su numeričke varijable kod kojih je nula je ishodište mjerenja i upućuje na nepostojanje svojstva koje se mjeri. U slučaju ovih varijabli omjeri među brojevima odgovaraju omjerima u stvarnosti. Npr., omjerne varijable su visina ili težina.

Mjerenje varijabli podrazumijeva dodjeljivanje brojeva onim svojstvima koja se mjere. Prema tome, podaci koji se prikupljaju kvantitativnim metodama istraživanja imaju formu numeričkih pokazatelja. O karakteru pojava koje se istražuje govori se u terminima frekvencija, postotaka, indeksa, tj. u terminima numeričkih vrijednosti. Zbog toga je i poznavanje statističkih tehnika obrade podataka jedan od nužnih preduvjeta pravilne interpretacije podatka prikupljenih kvantitativnim metodama istraživanja.

Najčešće korištene kvantitativne metode istraživanja u komunikacijskim znanostima su *metoda ankete i metoda analize sadržaja*[^16]. Metodom ankete uglavnom se istražuju navike u konzumaciji medija, stavovi prema medijima, povjerenje u medije, razina medijske pismenosti, reakcije na pojedine komunikacijske kampanje i tsl. Metodom analize sadržaja istražuje se zastupljenost pojedinih tema u medijskim objavama, način na koji mediji govore o pojedinim događajima, kako prezentiraju pojedine društvene aktere, koje poruke odašilju i tsl. Upravo zbog njihovog intenzivnog korištenja, u poglavljima koja slijede podrobnije će biti opisana osnovna svojstva i osnovna izvedbena pravila u korištenju ovih dvaju metoda.

## Priprema istraživanja posredstvom kvantitativnih metoda

Proces istraživanja posredstvom kvantitativnih metoda sastoj se od logičkog slijeda postupaka koje treba provesti kako bi se došlo do pouzdanih i valjanih informacija. Ti se postupci obično svrstavaju u nekoliko međusobno povezanih faza (Halmi, 1999:37).

1.  Definiranje problema i ciljeva istraživanja

2.  Postavljanje hipoteza

3.  Određivanje izvora podataka i nacrta istraživanja

4.  Određivanje metoda

5.  Uzorkovanje

6.  Analiza podataka i interpretacija rezultata istraživanja

7.  Pisanje istraživačkog izvještaja (znanstveni članka, monografija, istraživački izvještaj i tsl.)

Realizacija istraživanja posredstvom kvantitativnih metoda podrazumijeva pažljivo planiranje svih navedenih faza istraživanja, definiranje istraživačkih procedura i određenje načina njihove kontrole.

Planiranje i priprema kvantitativnog istraživanja obavlja se u posredstvom izrade **nacrta istraživanja**. Nacrt istraživanja je sistematski strukturiran plan istraživačkog procesa u kojemu je dokumentiran način na koji istraživač želi pristupiti planiranom istraživanju kao i procedure koje želi koristiti. Nacrtom istraživanja se osigurava:

-   Sistematičnost istraživanja: jasno definiranje ciljeva i hipoteza te izbora metoda.

-   Metodičnost istraživanja: svi postupci koji će biti poduzeti u istraživanju unaprijed su planirani.

Nacrtom istraživanja istraživač prije same realizacije istraživanja želi pružiti koncizne odgovore na sljedeća pitanja:

-   Što je predmet istraživanja?

-   Što su ciljevi istraživanja?

-   Koja je osnovna(e) hipoteza(e) od koje se kreće u istraživanje?

-   Kako je operacionaliziran teorijski koncept od kojeg se kreće u istraživanje?

-   Koja metoda istraživanja će se koristiti i na koji način?

-   Kako će se postupati s podacima u fazi njihove obrade?

Struktura nacrta istraživanja nije strogo kodificirana, no obično se nacrt istraživanja strukturira posredstvom sljedećih poglavlja.

1.  **Uvod**

U uvodu se obično ukratko naznačuje predmet istraživanja, navodi se što je u fokusu interesa istraživanja, zbog čega je istraživanje znanstveno i društveno relevantno. Može se naznačiti i širi teorijski okvir iz kojeg se kreće u istraživanje te eventualno opisati kakve su očekivane znanstvene i društvene konzekvence istraživanja koje se namjerava provesti.

1.  **Predmet istraživanja**

U ovom poglavlju detaljno se opisuje predmet istraživanja. Specificiraju se njegova najvažnija obilježja koja su predmet interesa te njegova znanstvena, stručna ili društvena relevantnost. Također, obično se navode ili konkretni teorijski razlozi ili neki drugi razlozi koji motiviraju usmjeravanje istraživačke prakse na izabrani predmet istraživanja. Primjerice, neki od mogućih predmeta istraživanja u komunikacijskim znanostima mogu se definirati na sljedeći način: *povjerenje u medije, razine medijske pismenosti u općoj populaciji, struktura medijskih publika ili doseg dnevnih novina.*

2.  **Teorijski pregled (i) definiranje osnovnih pojmova**

Teorijski pregled ili teorijski okvir dio je nacrata istraživanja u kojem se upućuje na postojeće teorije koje su relevantne za proučavanje izabranog predmeta istraživanja ili na onu teoriju od koje se kreće u istraživanje. Dakle, ovdje se upućuje na glavna teorijska određenje predmeta istraživanja koja su već razvijena u okviru znanosti ili na određene teorijske propozicije unutar jedne ili više relevantnih teorija koje se žele empirijski testirati. Smisao ovog poglavlja može se pronaći i u predstavljanju važećih teorija iz područja istraživanja te njihove kritičke usporedbe (Tkalac Verčić, Sinčić Ćorić, Pološki Vokić, 2010).

3.  **Ciljevi istraživanja**

Ciljevi istraživanja predstavljaju konkretne „zahtjeve" za pojedinim tipovima podataka, informacija ili spoznaja, tj. podrazumijevaju precizno određivanje onoga što se istraživanjem želi postići. Njihova realizacija omogućuje spoznaju onih obilježja predmeta istraživanja koja su od predmeta istraživačkog interesa. Dakle, pomoću ciljeva istraživanja istraživač određuje što želi saznati o predmetu istraživanja.

Prilikom definiranja ciljeva istraživanja bitno je sljedeće:

1.  Ciljevi istraživanja moraju se moći realizirati!

2.  Ne smiju biti preopćeniti *(* npr*. utjecaj medija na mlade).*

3.  Ukoliko je potrebno moguće je definirati jedan generalan cilj istraživanja i više specifičnih ciljeva istraživanja[^17].

Ciljevi istraživanja obično se navode takstativno, npr.:

1.  Utvrditi čitanost pojedinih rubrika dnevnih novina.

2.  Odrediti najpopularnije rubrike u dnevnim novinama.

3.  Definirati razloge čitanosti dnevnih novina.

4.  Utvrditi socio-demografsku strukturu čitatelja dnevnih novina.

4.  **Hipoteze**

Kao što smo naveli, kvantitativne metode istraživanja uobičajeno se koriste kada se istraživanjem želi testirati neka hipoteza(e). Dakle, uobičajeni idealtipski postupak kvantitativnih istraživanja podrazumijeva izvođenje hipoteza iz određene teorije. Temeljem prikupljenih empirijskih podataka one se ili potvrđuju ili odbacuju. Shodno tome teorija od koje se kreće u istraživanje se odbacuje ili potvrđuje ili modificira.

Zbog navedenog, jedan od uobičajenih dijelova nacrta istraživanja je i onaj u kojem se specificiraju hipoteze od kojih se kreće u istraživanje. Vujević hipoteze definira kao misaone odnose među pojmovima (Vujović, 2006:86), a Halmi kao nedokazanu tvrdnju, pretpostavku koja se empirijski može provjeriti (Halmi, 1999:38). Hipoteza treba ispunjavati sljedeće uvjete (Milas, 2009:69).

-   Mora biti primjerena problemu / predmetu istraživanja.

-   Mora biti jasna i nedvosmislena, postavljena na način koji dopušta opovrgavanje.

-   Mora biti najjednostavniji mogući odgovor na problem.

-   Mora biti razložna i vjerojatna prije same provjere.

-   Mora biti provjerljiva.

Da bi hipoteza bila provjerljiva, potrebno ju je izraziti u mjerljivim terminima (Tkalac Verčić, Sinčić Ćorić, Pološki Vokić, 2010). „Pretvaranje" teorijskih pojmova u mjerljive varijable naziva se *operacionalizacija*. Dakle, operacionalizacijom se prelazi s teorijskog na empirijski aspekt istraživanja – teorijski pojmovi transformiraju se u mjerljive entitete. Zbog tog razloga i hipoteze se uobičajeno definiraju kao pretpostavljeni odnos između varijabli koje se istraživanjem mjere. Primjerice, često se hipoteza određuje kao pretpostavljeni suodnos između neke nezavisne i zavisne varijable.

**Nezavisne varijable** su one za koje se smatra da ovisno o njihovoj varijaciji variraju i neke druge varijable. **Zavisne varijable** su one koje variraju zavisno od varijacija nezavisne varijable. Npr., ukoliko kao nezavisnu varijablu odredimo dob čitatelja dnevnih novina, a kao zavisnu učestalost čitanja dnevnih novina, tada možemo postaviti sljedeću istraživačku hipotezu: *osobe starije od 45 godina češće čitaju dnevne novine od osoba mlađih od 45 godina.*

Specifičan tip hipoteze koji je karakterističan u kvantitativnim istraživanjima je tzv. **nul-hipoteza**. Naziva se još i „statističkom hipotezom". Postavlja se pri provedbi statističkih testova, primjerice kada se želi testirati statistička značajnost razlika između različitih grupa sudionika istraživanja dobivenih nekim mjerenjem dobivenih nekim mjerenjem. Naziva se nul-hipoteza, jer je postavljena u niječnom obliku (Milas, 2009:71), a podrazumijeva pretpostavku da razlike između grupa ne postoje, tj. da je razlika između grupa nula. Ukoliko se testiranjem utvrdi da razlike postoje, nul-hipoteza se odbacuje. Također, nul-hipoteza se koristi i u korelacijskim analizama, a pretpostavlja nepostojanje pozvanosti između testiranih varijabli.

Primjer nul-hipoteze: *Ne postoji statistički značajna razlika u prosječnoj vrijednosti muškaraca i žena na testu medijske pismenosti*.

5.  **Varijable**

Obično se u nacrtu istraživanja prezentira i popis glavnih varijabli koje će se mjeriti te se definira njihova funkcija (npr. zavisne i nezavisne varijable) kao i pretpostavljeni odnos (korelacijski ili kauzalni). Izbor varijabli koje će se mjeriti u istraživanju mora proizlaziti iz postavljenih ciljeva istraživanja i definiranih hipoteza. Dakle, istraživanjem nema smisla mjeriti one varijable koje su s obzirom na predložene ciljeve i hipoteze nepotrebne.

6.  **Izvori podataka i metode istraživanja**

U nacrtu istraživanja potrebno je jasno definirati izvore i metode prikupljanja podataka. Izvori podataka mogu biti primarni i sekundarni. Sekundarni izvori su oni koji postoje neovisno od samog istraživača, tj. koji sadrže već prikupljene podatke. Npr. rezultati prijašnjih istraživanja, arhivska građa, dokumentacija i tsl. Kada se koriste sekundarni izvori podataka govori se da se obrađuju „sekundarni podaci". Analiza takvih tipova podataka obično se naziva i *desk analiza* ili *analiza za stolom*. Primarni podaci su oni podaci koji su prikupljeni u samom istraživanju koji se prikupljaju u okviru istraživačkog projekta koji se provodi.

Kvantitativne metode koje su na raspolaganju istraživaču za prikupljanje primarnih podataka primjerice mogu biti metoda ankete, metoda analize sadržaja ili metoda eksperimenta. U ovom poglavlju nacrta istraživanja istraživač navodi koju metodu će koristiti (npr. telefonska anketa), može ukratko objasniti razloge zbog kojih je planira koristiti te predočiti osnovna obilježja mjernog instrumenta. To znači da se upućuje na strukturu upitnika, tematske blokove i broj pitanja, vrste ljestvica ili na strukturu matrice za analizu sadržaja.

Također, obično se u posebnom podpoglavlju upućuje i na vrstu i veličinu uzorka na kojem se provodi istraživanje. Dakle, potrebno je izvijestiti o planiranom broju sudionika istraživanja te o tome hoće li se istraživanje provesti na slučajnim ili neslučajnim uzorcima. Uz to obično se opisuje proces uzorkovanja, tj. objašnjava se kakav je konkretan plan izbora jedinca uzorka.

7.  **Plan statističke obrade podataka**

Navodi se koje se procedure statističke obrade podataka namjeravaju koristiti.

8.  **Terminski plan**

Ukoliko je potrebno razrađuje se terminski plan provedbe svih faza istraživanja.

Važno je napomenuti da je nacrt istraživanja u slučaju kvantitativnih metoda u pravilu „fiksiran", tj. zatvoren. Iako to nužno ne mora biti pravilo, on se u pravilu ne mijenja tijekom samog istraživanja. Primjerice, rijetko se postavljaju novi ciljevi istraživanja ili se nadodaju nove hipoteze ili nove metode. Prema tome, istraživači u slučaju provedbe istraživanja posredstvom kvantitativnih metoda istraživanja uglavnom ostaju u metodskim i izvedbenim gabaritima koji su predviđeni nacrtom istraživanja. U pravilu, nacrt kvantitativnog istraživanja ne mijenja se tijekom samog istraživačkog postupka.


## Priprema istraživanja posredstvom kvalitativnih metoda

Za razliku od istraživanja koja se provode kvantitativnim metodama, istraživanja koja se provode kvalitativnim metodama u znatno većoj mjeri su „otvorenog dizajna". To znači da je nacrt istraživanja nije „fiksiran" već je otvoren za promjenu i doradu tijekom samog istraživanja. Tijekom samog istraživanja moguće je postavljati nova istraživačka pitanja, predlagati uvođenje novih sudionika istraživanja ili uvoditi nove metode istraživanja.

Upravo je otvorenost dizajna jedna od ključnih odrednica samog procesa istraživanja. Willig (2016) napominje da kvalitativne metode istraživanja moraju biti dovoljno fleksibilne kako bi dozvolile izranjanje novih i nepredviđenih kategorija značenja i iskustva.

Nacrt kvalitativnog istraživanja ugrubo možemo podijeliti u nekoliko poglavlja. Kao i u slučaju kvantitativnih istraživanja, u poglavlju „Predmet istraživanja" potrebno je opisati predmet i temu istraživanja. Uz ovo poglavlje, sugeriramo da se nacrt kvalitativnog istraživanja strukturira na način da u njemu budu uključene komponente koje sugerira Maxvell (2012). To su:

-   Ciljevi.

-   Konceptualni kontekst.

-   Istraživačka pitanja.

-   Metode.

-   Valjanost

U poglavlju *Ciljevi* obično se ekspliciraju razlozi zbog kojih se provodi istraživanje. Primjerice, može se navesti zbog čega se istraživanje smatra vrijednim za provesti, što se njim želi razjasniti, što se želi zaključiti i tsl.

Iduća komponenta nacrta istraživanja može se definirati kao *Konceptualni kontekst*. Konceptualni kontekst zapravo je sistem koncepata, očekivanja, pregled literature i teorija koje podupiru i koje istraživača informiraju o predmetu istraživanja.

Središnji dio nacrta kvalitativnog istraživanja su *Istraživačka pitanja*. Ona su ujedno i glavni moment razlikovanja kvalitativnog istraživačkog dizajna od kvantitativnog. Naime, u slučaju kvantitativnog dizajna postavljaju se ciljevi istraživanja i hipoteze koje se obično deduciraju iz neke općenite teorije koja se istraživanjem testira. U slučaju kvantitativnog istraživanja hipoteze i ciljevi istraživanja supstituiraju se istraživačkim pitanjima. Istraživačka pitanja usmjeravaju istraživanje na ono što se njime želi otkriti. U suštini radi se o izdvajanju određenih aspekata fenomena koji se istražuje, a za koje je istraživač zainteresiran. Na taj način pokušava se bolje fokusirati ili usmjeriti samo istraživanje (Willig, 2016:117). Bitno je napomenuti da formulacija istraživačkih pitanja ima konzekvence i u pogledu izbora metoda istraživanja. Primjerice, ukoliko su istraživačka pitanja postavljena na način da su usmjerena prema deskripciji iskustva aktera u određenom događaju, to znači da se kao metoda nameću intervjui ili fokus grupe. Ukoliko su usmjerena prema opisu nekih oblika ponašanja koje je vizualno dostupno, kao metoda se nameće promatranje. Drugim riječima, pojedina istraživačka pitanja određuju i izbor samih kvalitativnih metoda koje se mogu koristiti u istraživačkom projektu.

Iduće poglavlje u dizajnu kvalitativnog istraživanja može se nasloviti kao *Metode*. U ovom poglavlju navode se metode istraživanja koje se planiraju koristiti te se legitimiraju razlozi zbog kojih se planiraju koristiti. Izuzev navođenja metoda, u ovom poglavlju prezentira se i početna ideja o vrsti materijala koji će se analizirati kao i o uzorku koji će biti obuhvaćen istraživanjem. Primjerice, ukoliko se istraživanje planira provesti analizom diskursa potrebno je navesti koji su izvori materijala koji će se analizirati. Ukoliko se provode intervjui ili grupne diskusije potrebno je navesti tko će biti sudionici istraživanja, kakva su njihova obilježja temeljem kojih će se izabirati, koliki broj intervjua ili diskusija se planira realizirati.

Maxwell predlaže da se prilikom dizajna kvalitativnog istraživanja pažnja obrati i na način validacije podataka. Dakle, istraživač na kraju nacrta istraživanja može navesti procedure i postupke koje će koristiti kako bi bio siguran da su njegove interpretacije i zaključci valjani.

Naposljetku, još jednom je potrebno napomenuti da je nacrt istraživanja u slučaju kvalitativnih metoda nije fiksiran. On je podložan promjenama. Sasvim je legitimno da istraživač tijekom samog istraživanja donosi odluku o postavljanju novih istraživačkih pitanja, korištenju alternativnih metoda ili promjeni uzoraka sudionika ili izvora građe koja se podvrgava analizi. Otvorenost dizajna istraživanja, njegova fleksibilnost, inherentna je karakteristika istraživanja koje se provode kvalitativnim metodama istraživanja.

**Uzorkovanje i vrste uzorka u kvalitativnim metodama istraživanja**

Najčešći cilj kvantitativnih istraživanja je procjena populacijskih parametara. Stoga kvantitativni istraživači obično nastoje smanjiti pristranost u istraživanju tako što žele osigurati da njihov uzorak precizno reprezentira populaciju iz koje je ekstrahiran (Murphy, 2020). Zbog tog razlog kvantitativne tehnike uzorkovanja su dizajnirane tako da prvenstveno minimiziraju pristranosti u izoru jedinica uzorka iz populacije te maksimiziraju generabilnost prikupljenih podataka (Koerber i McMichael, 2008). Umjesto da smjeraju generalizaciji podataka s uzorka na populaciju, uobičajena svrha kvalitativnih istraživanja može se opisati sintagmom „pogleda kroz prozor" ili „zrcaljenja" specifične situacije ili fenomena koji se proučava (Giacomini i Cook, 2000: 470). Drugim riječima, načelo reprezentativnosti u kvalitativnim istraživanjima nije ključno načelo uzorkovanja, tj. logika uzorkovanja u kvalitativnim istraživanjima prilično je drugačija.

Uzorkovanjem u kvalitativnim istraživanjima, bez obzira o kojoj vrsti kvalitativnog materijala se radi, želi se mimimizirati mogućnost da rezultati istraživanja budu drugačiji no što bi bili da se istraživanje provodi od strane drugih istraživača, te da su istraživanjem obuhvaćeni neki drugi individualni slučajevi unutar skupa onih slučajeva koji su relevantni za problem istraživanja (Koerber i McMichael, 2008: 463).

Razvojem kvalitativnih metoda istraživanja isprofilirali su se i uobičajeni tipovi uzoraka koji se koriste u kvalitativnim istraživačkim projektima. To su prigodni uzorak, svrhoviti uzorak (može se koristiti i termin „namjerni") te teorijski uzorak.

**Prigodni uzorak**

Prigodni uzorak u kvalitativnim istraživanjima ima svojstva istoimenog uzorka koji se koristi u kvantitativnim istraživanjima (objašnjeno u poglavlju...). Dakle, riječ je o takvom odabiru u kojem koristimo one sudionike koji su nam u trenutku regrutacije bili na raspolaganju. Primjerice, u uzorak uključujemo osobe koje se odazovu na poziv za sudjelovanje (primjerice poziv za sudjelovanje u istraživanju objavi se na društvenim mrežama), kad istraživač prihvatit bilo koga koji se zatekne na mjestu provođenja istraživanja ili kad odluči da se u odabiru neće baviti suštinskim zahtjevima uzorkovanja.

**Svrhoviti uzorak**

Svrhoviti uzorak podrazumijeva odabir onih sudionika istraživanja koji mogu pružiti adekvatne informacije kao odgovore na postavljena istraživačka pitanja. Dakle, riječ je o pristupu u kojem se koristi strategija odabira sudionika po nekom kriteriju koji obično osigurava izbor onih osoba koje su relevantnije, npr. informiranije, ili imaju bogatije iskustvo, u vezi teme koja je predmet istraživanja. Postoje tri podvrste svrhovitog uzorka koje se obično koriste u kvalitativnim istraživanjima.

*Uzorak tipičnih slučajeva*: subjekti istraživanja su osobe koje su s obzirom na svoje iskustvo, način života, vrstu socijalnih interakcija one koje su najrelevantnije za fenomen koji možemo istražiti. Relevantnost njihovog iskustva osnovna je garancija valjanosti rezultata istraživanja. Primjerice, provodi se istraživanje kako bi se spoznale navike u izradi Instagram storya u Z generaciji. U ovom slučaju uzorak tipičnih slučajeva mogli bismo konstruirati na sljedeći način. Temeljem kvantitativnih podataka o korištenju Instagrama i izradi Instagram storija možemo doći do informacija koliko često prosječan korisnik Instagram iz Z generacije kreira storije. Ako je to jednom tjedno, tada ćemo u uzorak uključiti one pripadnike Z generacije koji jednom tjedno kreiraju Instagram storije.

*Uzorak maksimalnih varijacija*: sudionici istraživanja su osobe s raznolikim iskustvima ili karakteristikama relevantnim za fenomen koji je predmet istraživanja. Prema tome, u uzorak se uključuju sudionici koji su relevantni za određeni socijalni fenomen, bez obzira na "stupanj" njihove relevantnosti / involviranosti / informiranosti ili neku drugu karakteristiku". Dakle, uzorkovanjem se želi postići raznolikost sudionika istraživanja koji se tretiraju kao relevantni za fenomen, s obzirom na njihove karakteristike, iskustva, rutine ili stavove. Primjerice, ukoliko metodom intervjua istražujemo pripadnike Z generacije koji kreiraju Instagram storije, tada ćemo u istraživanje uvrstiti ispitanike koji se međusobno razlikuju s obzirom na intenzitet kreiranja storija. Primjerice, planiramo uzorak od 15 ispitanika od kojih će 5 biti oni koji izrađuju storije jednom mjesečno ili rjeđe, 5 onih koji će kreirati storije nekoliko puta mjesečno te 5 koji ih kreiraju jednom tjedno ili češće.

*Uzorak devijantnijih slučajeva* (može se koristiti i termin „uzorak atipičnih slučajeva"): subjekti istraživanja su osobe koje su s obzirom na svoje iskustvo, način života, vrstu socijalnih interakcija one koje predstavljaju određeni izuzetak od "očekivanih pravila". Kada želimo istražiti neke pojave ili aspekte pojava koje se pojavljuju kao devijacije ili izuzeci. Dakle, istraživači namjerno biraju slučajeve koji su atipični, ekstremni, rijetki ili odstupaju od „pravila" ili općeg obrasca. Primjerice, u uzorka uključujemo korisnike Instagrama, ali koji nikada ne kreiraju Instagram storije.

**Teorijski uzorak**

Ovo je uzorak osoba (ili neke druge građe) odabranih postupno, tijekom procesa istraživanja. Riječ je o tome da se analitički materijal ili sudionici istraživanja izabiru se po kriteriju relevantnosti za istraživačko pitanje, teorijsku poziciju, analitički okvir ili teoriju koja se razvija. U teorijskom uzorkovanju obično se polazi od pretpostavke da kriteriji uzorkovanja postaju vidljivi tek nakon što se započne s istraživanjem, tj. da je strukturu uzorka moguće mijenjati shodno spoznajama do kojih se dolazi u istraživanju. Drugim riječima, nove spoznaje do kojih se dolazi tijekom istraživanja mogu promijeniti pretpostavke o potrebnoj strukturi uzorka, mogu utjecati na spoznaju da su potrebni novi ispitanici, koji se po nekim obilježjima razlikuju od prvobitno planiranih, a koji će donijeti neku novu spoznajnu kvalitetu. Ova koncepcija uzorkovanja dolazi iz tzv. utemeljene teorije (eng. Groundet Theory) koja je detaljnije objašnjena u poglavlju Utemeljena teorija i kodiranje.

[^14]: Napomena o nominalnim varijablama

[^15]: Napomena o intervalnim varijablama

[^16]: Vidi poglavlja o anketi i analizi sadržaja

[^17]: Napomena o ciljevima istraživanja
