# Razvoj komunikologije: utemeljitelji i prva istraživanja

Naveli smo da razvoj komunikologije započinje u prvoj polovini dvadesetog stoljeća u SAD-u.
Bitno obilježje tog razvoja je multidisciplinarnost i policentričnost: prva komunikološka
istraživanja razvijaju se u okviru različitih neovisnih istraživačkih grupa i od strane znanstvenika
s različitim disciplinarnim zaleđem. Primjerice, Hovland–Yale istraživačka grupa, koja je svoja
istraživanja fokusirala na pitanja promjene stavova uslijed medijskih utjecaja, proizašla je iz
psihologije. Istraživačku grupu koju je predvodio Paul Lazarsfeld, a koja se bavila istraživanjem
slušanosti radija i njegovih utjecaja na Sveučilištu Columbia, činili su sociolozi. Istraživanja
Harolda Lasswella i njegovih suradnika inklinirala su prema političkim znanostima i pravu.
Grupu istraživača Wilbura Schramma u Illinoisu u početku su činili humanisti i novinari. Prema
tome, komunikologija kakvu poznajemo danas posljedica je djelovanja na različitim
znanstveno-istraživačkim područjima (McGuire, 1996: 39).U nastavku su pobliže predstavljene
aktivnosti trojice znanstvenika koji su u dali značajan doprinos razvoju komunikologije. Njihov
znanstveni rad zorno zrcali spomenute interdisciplinarne korijene komunikologije, ali i upućuje
na istraživačka pitanja koja su u velikoj mjeri potakla njen razvoj. Riječ je o Carlu Hovlandu,
Paulu Lazarsfeldu i Kurtu Lewinu.
Carl Iver Hovland
Carl Hovland djelovao je na Sveučilištu Yale. Njegov istraživački tim u povijesti komunikologije
poznat je i pod nazivom Hovland–Yale istraživačka grupa. Predmet Hovlandovog interesa
odnosio se na to kako različiti dijelovi persuazivne komunikacije doprinose promjeni stavova
(McGuire, 1996). Rogers (1997) navodi da je teorijski okvir Hovlandovih istraživanja sačinjen
od kombinacije biheviorizma i psihoanalitičke teorije. Također, utjecaj na njegov rad imala je
teorija učenja Clarka Hulla, prema kojoj se promjena stava promatra kao proces učenja novih
odgovora na određene podražaje.
Hovlandov istraživački tim u značajnoj mjeri koristio se eksperimentalnim metodama
posredstvom kojih se pokušavala pronaći povezanost između izloženosti komunikaciji i
promjene stavova. Primjerice, zanimalo ga je kako na promjene stavova utječu čimbenici kao
što su raspored iznošenja činjenica unutar komunikacije, karakterne osobine, efekti sporog

vremenskog reagiranja (Rogers, 1997). Eksperimentalna istraživanja koja je provodio
doprinijela su brojnim spoznajama na području proučavanja metoda persuazije. Primjerice, iz
njih su proizašle brojne spoznaje vezane uz djelotvornost propagande kao što su važnost
pouzdanosti izvora, efekt spavača, učinak jednostranih i dvostranih poruka, učinak straha na
gledatelja (Rogers, 1997).
Tijekom II. svjetskog rata (1942. godine) Hovland napušta sveučilište te prelazi u Research
Branch of the Information and Education Division u U.S. Department of War. U okviru ove
institucije istražuje utjecaj propagandnih filmova poput Why We Fight na moral i motivaciju
vojnika. U jednom širem smislu, ova istraživanja bavila su se općenitim utjecajem audio-
vizualnih sadržaja na stavove ljudi.
Kao Hovlandov najznačajniji teorijski doprinos komunikologiji obično se ističe onaj prema
kojemu vjerodostojni izvori rezultiraju intenzivnom promjenom stavova neposredno nakon
komunikacijskog akta. Međutim, uslijed tzv. efekta spavača (sleeper effect), tijekom proteka
vremena izvor se zaboravlja. To dovodi do neobičnog fenomena u kojem poruka koja je u
početku bila odbačena zbog nevjerodostojnog izvora, s vremenom dobiva na utjecaju jer
primatelji pamte sadržaj poruke, ali zaboravljaju negativni izvor. Dakle, utjecaj izvora je
najintenzivniji nakon konzumacije poruke, a protekom vremena slabi. Jednostrane poruke
rezultiraju intenzivnijom promjenom stavova u slučaju publika koje čine osobe nižeg
obrazovanja, dok dvostrane poruke rezultiraju intenzivnijom promjenom stavova
obrazovanije publike. Pojedinci koji su snažno privrženi grupi u manjoj mjeri bit će spremni
promijeniti stavove u pogledu pitanja koja su oprečna grupnim normama / standardima
(Rogers, 1997).
Paul Lazarsfeld
Ovaj austrijski, a potom i američki matematičar, sociolog i komunikolog jedan je od onih za
koje se bez imalo pretjerivanja može konstatirati da su ostavili dubok, gotovo neizbrisiv trag u
povijesti znanosti kojom su se bavili. Njegovo djelo ne samo da ima veliko kulturno-povijesno
značenje za sociologiju, politologiju i za komunikacijske znanosti, već je i dalje u mnogim
aspektima živo i relevantno (Burić, 2025). Teorijski doprinos Paula Lazarsfelda komunikologiji
najizraženiji je u razvoju teorije dvostupanjskog tijeka komunikacije (engl. two-step flow of

communication). Ona apostrofira da stvaratelji javnog mnijenja (engl. opinion leaders) čine
premosnicu između medija i publike u nekoj zajednici. Dakle, mediji masovne komunikacije
prije svega utječu na stvaratelje javnog mnijenja koji zatim u procesima socijalnih interakcija s
drugim članovima zajednice šire informacije. Također, rezultati Lazarsfeldovih istraživanja
upućuju na to da je utjecaj komunikacijskih kampanja relativno malen. Primjerice, Lazarsfeld
navodi da u slučaju predizbornih kampanja mediji uglavnom pojačavaju već oformljene
stavove, a ne mijenjaju biračko opredjeljenje4.
Lazarsfeld je podrijetlom iz Austrije gdje se već kao mladi znanstvenik počinje baviti
empirijskim medijskim istraživanjima. Prva poznatija Lazarsfeldova studija (1933.) bila je ona
o nezaposlenosti u Marienthalu, mjestašcu nedaleko od Beča. U ovom projektu, koji ima
mnoga obilježja akcijskog istraživanja, za svoj metodološki pristup Lazarsfeld je koristio naziv
sociografija. Nakon emigriranja u SAD, radi na Sveučilištu Columbia gdje je osnovao i vodio
Bureau of Applied Social Research. Također, Lazarsfeld se bavio i komercijalnim, tržišnim
istraživanjima, primjerice istraživanjima ponašanja potrošača. Upravo u kontekstu njegovih
brojnih istraživačkih interesa i brojnih istraživačkih projekata koje je provodio treba promatrati
i njegove metodološke inovacije, posebice u razvoju kvantitativnih metoda istraživanja.
Naime, Lazarsfeld nije bio samo praktičar, već i značajan metodski inovator. Primjerice, jedan
je od pionira mehaničkog/elektroničkog mjerenja stavova. Osmislio je tzv. Program-Analyzer
kojim je testirao stavove o radijskom sadržaju5. Rogers (1997) navodi da su dva značajna
Lazarsfeldova metodološka doprinosa, koji su potekli iz projekata radijskih istraživanja, bili
upravo Program Analyzer te fokus-grupe (Rogers, 1997). Dao je i značajan doprinos u pogledu
promocije istraživanja na tzv. panel-uzorcima. Panel-uzorci sačinjeni su od osoba koje
sudjeluju u dva ili više valova istraživanja6. Lazarsfeld je ovakav uzorak koristio u istraživanju
People's Choice budući da je želio utvrditi je li došlo do promjene političkog opredjeljenja
nakon što su sudionici istraživanja bili izloženi predizbornoj kampanji (Rogers, 1997)7.
4 Svoju teoriju razvija temeljem podataka prikupljenih u istraživanju People's Choice, provedenom tijekom
predsjedničke kampanje 1940. godine u državi Ohio.
5 Uređaj je funkcionirao na način da su sudionici istraživanja pritisnuli zelenu tipku u slučaju kada im se program
sviđao, a crvenu u slučaju kada im se nije sviđao.
6 Primjerice, istraživanje se provodi u dva vala. U oba vala uzorak sudionika istraživanja čine iste osobe.
7 Svega su 54 od 600 ispitanika promijenila mišljenje o tome za koga će glasati, a samo ih je nekoliko to učinilo
pod utjecajem medijske kampanje.

Također, Lazarsfeldovu značajnu metodološku inovaciju predstavlja teorija o latentnoj
strukturi. Njome se inaugurira ideja postojanja latentnih dimenzija kojima se može objasniti
povezanost između različitih manifestnih indikatora mjerenih pojava. Lazarsfeld ističe da
pojedini socijalni fenomeni predstavljaju kompleksne entitete koji se ne mogu neposredno
zamijetiti. No, da oni ipak postoje i djeluju, zaključujemo posredno, na temelju vanjskih
manifestacija koje možemo opaziti i mjeriti. Te vanjske pokazatelje nazivamo indikatorima
socijalnih fenomena, a samu pojavu latentnim obilježjem (Halmi, 1999: 21-22). Naposljetku,
Lazarsfeld je jedan od prvih društvenih znanstvenika koji je promovirao metodski pristup koji
danas nazivamo mješovita metodologija. Surađujući sa sociologom Robertom K. Mertonom,
prvi je počeo kombinirati upotrebu kvantitativnih metoda istraživanja (npr. anketa) i
kvalitativnih metoda istraživanja (dubinskih intervjua ili fokus-grupa). Bio je izraziti zagovornik
metodske trijangulacije, tj. korištenja većeg broja različitih metoda u okviru jednog
istraživačkog projekta.
Cjelokupna profesionalna karijera i akademski rad Paula Lazarsfelda bio je posvećen samo
jednom cilju: mjerenju društva. Paul Lazarsfeld želio je izmjeriti društvo na način na koji pri
Svega su 54 od 600 ispitanika promijenila mišljenje o tome za koga će glasati, a samo ih je
nekoliko to učinilo pod utjecajem medijske kampanje. rodoslovci mjere prirodu ili psiholozi
psihičke procese! Mjerio je gotovo sve što je u društvu mogao učiniti mjerljivim, bilo da se radi
o odnosu društva i ekonomije, o potrošačkim navikama ljudi, o odnosu društva i medija
masovne komunikacije kao i medijskim utjecajima ili o političkom ponašanju. U tu svrhu
razrađivao je metode istraživanja, konstruirao mjerne instrumente, osmišljavao tehnike
obrade podataka, tj. činio sve što je mogao kako bi društvo prestalo biti isključivo objekt
mišljenja i postalo objekt mjerenja. Stoga nije riječ samo o jednom od najvećih metodoloških
inovatora u povijesti društvenih znanosti, već je i riječ o znanstveniku koji ih je snažno usmjerio
prema onoj formi društveno-znanstvenog bavljenja koja i danas dominira, a koju francuski
sociolog Michel Lallement u svom djelu Povijest socioloških ideja naziva instrumentalni
pozitivizam (Burić, 2025). I pola stoljeća nakon njegove smrti, zasade Lazarsfeldovog rada
snažno utječu na razmišljanja, ne samo o tome kako istraživati, već i kako na temelju
empirijskih podataka valjano zaključivati o društvenom svijetu.

Wilbur Schramm
Wilbur Schramm stekao je obrazovanje na području humanističkih znanosti (doktorat iz
književnosti), a na početku karijere radio je kao novinar. Nakon izbijanja Drugog svjetskog rata,
Schramm je dvije godine služio kao ravnatelj obrazovanja u Uredu za činjenice i brojke (Office
of Facts and Figures) vlade SAD-a, a zatim u Uredu za ratne informacije. Schrammovo ratno
istraživanje, koje se ticalo propagande, pridonijelo je produbljivanju njegova interesa za
korištenje masovne komunikacije kao alata za utjecaj na javno mnijenje. Godine 1943.
Schramm se vratio na Sveučilište u Iowi, a 1947. se preselio na Sveučilište Illinois, gdje je
osnovao Institut za istraživanje komunikacija i bio njegov direktor. Godine 1955. osniva Institut
za istraživanje komunikacija na Sveučilištu Stanford.
Jedan od njegovih ključnih doprinosa je razumijevanje kako informacije putuju kroz različite
kanale i kako se razmjenjuju među ljudima. Ovaj model prikazuje komunikaciju kao proces u
kojem je bitno da postoje "pošiljatelj", "poruka", "primatelj" i "povratna veza". Schramm je
smatrao da je komunikacija uspješna samo ako postoji zajednički kontekst između pošiljatelja
i primatelja, odnosno zajedničko polje iskustva ili kulture8.
Harold Lasswell
Politolog Harold Lasswell doktorirao je 1926. na temu političke propagande u vrijeme rata.
Ovom temom bavio se i tijekom Drugog svjetskog rata koristeći analizu sadržaja kako bi
proučavao propagandu saveznika i sila Osovine (Rogers, 1997). Uz Hovlanda, bio je jedan od
začetnika empirijskih istraživanja propagandnih učinaka, kao i začetnik korištenja
kvantitativnih metoda u istraživanjima komunikacijskih učinaka. Jedan je od prvih istraživača
koji je intenzivno koristio metodu analize sadržaja.
Nakon rata, Lasswell se uključuje u tzv. Hooverove studije u okviru projekta RADIR (Revolution
and the Development of International Relations). Metodom analize sadržaja, zajedno sa
suradnicima, obradio je 20.000 uvodnika (editorijala) u najprestižnijim novinama pet nacija.
Projekt je trajao od 1949. do 1953. godine, s ciljem proučavanja političkih i socijalnih promjena
8 Schramm, W. (2024). Wilbur Schramm. Encyclopedia Britannica. Dostupno na:
https://www.britannica.com/biography/Wilbur-Schramm, pristupljeno 10. 2. 2026.

koje su se dogodile od 1890. do 1950. Analiziranje velike količine empirijskih podataka u okviru
ovog projekta utjecalo je na daljnji razvoj kvantitativne analize sadržaja (Rogers, 1997).
Proučavanju komunikacije Harold Lasswell pristupao je interdisciplinarno. Na Sveučilištu u
Berlinu proučavao je psihoanalizu Sigmunda Freuda te je bio pionir njezine primjene u
američkim društvenim znanostima, posebice u politologiji. Načela Freudove psihoanalize
koristio je kao temelj analize djelovanja političkih vođa. Vjerovao je kako uz pomoć
psihoanalize može objasniti zašto su neki političari radikali, a neki konzervativci.
Jedan od najvećih doprinosa komunikologiji njegov je model komunikacije kojim objašnjava
glavna područja istraživanja komunikologije, tzv. Lasswellova formula: Who says what in which
channel to whom with what effect (Kunczik i Zipfel, 2006: 5). Lasswellova formula predstavlja
jedno od bazičnih određenja komunikologije budući da apostrofira glavne aktere
komunikacijskog procesa: aktere koji proizvode i diseminiraju medijske sadržaje (tko?),
medijski sadržaj – što se govori (što?), prijenosnike poruke – medije (kojim kanalima?),
primatelje poruke – medijsku publiku (kome?) te medijske efekte – direktne i indirektne
učinke medijske komunikacije (s kojim efektom?).
