# Literatura

Aaker, A. David, Kumar, V. Murty i Day, S. George (2008.) Marketinško istraživanje.
Ekonomski fakultet: Beograd.
Abercrombie, Nicholas, Hill, Stephen i Turner, Bryan, S. (2008). Rječnik sociologije. Zagreb:
Jesenski i Turk.
Afrić, Vjekoslav (1989.) Struktura sociološke teorije. Zagreb: Naprijed.
Bechhofer, F., Paterson, L. (2000). Principles of Research Design in Social Sciencies.London:
Routledge
Bickman, Leonard i Rog, J. Debra (1998.) Handbook of Applied Social Research Methods.
Thousend Oaks, London, New Delhi: Sage Publications.
Bilić, Paško (2020.) Sociologija medija. Rutine, tehnologija i moć. Zagreb: Naklada Jesenski
i Turk.
Bradburn, Norman, Sudman, Seymour i Wansink, Brian (2004.) Asking questions: The
definitive guide to questionnaire design for market research, political polls, and social and
health questionnaires. San Francisco: Jossey-Bass A Wiley Imprint.
Bulger, Monica (2012.) „Measuring Media Literacy in a National Context: Cahllenges of
Definition Mehod and Implementation“, Medijske studije (3) 6: 83-104.
Churchill, A. Gilbert i Iacobucci, Dawn (2002.) Marketing Research. Mehgodological
Fonudations. Mason: South Western.
Creswell, J.W. (2009) Research Design: Qualitative, quantitative and mixed method
approaches. Thousand Oaks: SAGE .
Creswell, J. W. i Plano Clark, V. L. (2007.) Designing and conducting mix methods research.
Thousand Oaks, London, New Delhi: Sage Publication.
Daymon, Christine, Immy, Holloway (2002.) Qualitative Research Methods in Public
Relations and Marketing Communications. London, New York: Routledge.

Dilthey, Wilhelm (1980.) Izgradnja historijskog svijeta u duhovnim naukama. Beograd:
BIGZ.
Durkheim, Emil (1999.) Pravila sociološke metode. Zagreb: Jesenski i Turk.
Elezović, Almir (2012.) „O čemu pišu novine? Analiza sadržaja novinskih naslovnica
(siječanj – lipanj 2011.)“, Medijska istraživanja, 18 (1): 61-88.
Fairclough, Norman (2003.) Analysing Discourse: Textual Analysis for Social Research,
London: Routledge.
Foddy, William (1993.) Constructing questions for Interviewing and Quesgtionnaires.
Cambridge: Cambridge University Press.
Giacomini, M. K., & Cook, D. J. (2000). Users’ guides to the medical literature XXIII.
Qualitative research in health care B: What are the results and how do they help me care
for my patients? Journal of the American Medical Association, 284, 478-482.
Geertz, Clifford (1973). Thick Description: Toward an Interpretive Theory of Culture. In The
Interpretation of Cultures (pp. 3–30). New York: Basic Books.
Glaser Barney i Strauss, Anselm (1967) The Discovery of Grounded Theory. Strategies of
Qualitative Research. New Brunswick. London: Aldine Transaction.
Halmi, Aleksandar (1996.) Kvalitativna metodologija u društvenim znanostima. Zagreb:
Pravni fakultet u Zagrebu.
Halmi, Aleksandar (1999.) Temelji kvantitativne analize u društvenim znanostima. Zagreb:
Alinea.
Halmi, Aleksandar i Crnoja, Josip (2003.) „Kvalitativna istraživanja u društvenim
znanostima i humanoj ekologiji“, Socijalna ekologija (12) 3-4: 195 – 210.
Hanh, Hans, Neurath, Otto i Carnap, Rudolf (2005.) Znanstveno shvaćanje svijeta – Bečki
krug. Zagreb: Hrvatski studiji sveučilišta u Zagrebu.
Hesse-Bieber, Nagy, Sharlene (2010.) Mixed Mehtods Research. Merging Theory with
Pratice. New York, London: The Guilford Press.

Holsti, R. Ole (1969). Content analysis for fhe social sciences and humanities. Boston:
Addison-Wesley.
Koerber, A., & McMichael, L. (2008). Qualitative Sampling Methods A Primer for Technical
Communicators. Journal of Business and Technical Communication, 22(4), 454–473.
https://doi.org/10.1177/1050651908320362
Krueger, Richard, Casey, Marry Anne (2000.) Focus Groups: A Practical Guide for Applied
Research. Thousand Oaks: Sage Publications.
Kuhn, S., Thomas (1999. [1962.]) Struktura znanstvenih revolucija. Zagreb: Naklada
Jesenski i Turk.
Kunczik, Michael i Zipfel, Astrid (2006.) Uvod u znanost o medijima i komunikologiju.
Zagreb: Zaklada Friedrich Ebert.
Jeđud, Ivana: (2007) Alisa u zemlji čuda – kvalitativna metodologija i metoda utemeljene
teorije. Hrvatska revija za rehabilitacijska istraživanja. 24 (2): str. 83-101.
Lakić, Igor (2009.) „Modeli analize diskursa novinskih članaka“, Riječ, 2: 91-108.
Lalić, Dražen i Kunac, Suzana (1999.) „Televizijski spotovi stranaka u predizbornim
kampanjama u Hrvatskoj 1995. i 1997.“, u: Vrcan, Srđan, Buklijaš, Boris, Lalić, Dražen,
Kunac, Suzana, Bulat, Nenad, Štrelov, Damir Pakiranje vlasti: Analiza izbora '95 i '97,
Zagreb: Alineja.
Lamza Posavec, Vesna (2021.) Metodologija društvenih istraživanja. Temeljni uvidi.
Zagreb: Institut društvenih znanosti Ivo Pilar.
Livingstone, Sonia (2004.) „Media literacy and the challenge of new information and
communication technologies“ [online]. London: LSE Research Online. Available at:
http://eprints.lse.ac.uk/1017 (1. 2. 2018.).
Marshall, Catharine i Rossman, B., Gretchen (2011.) Designin Qualitative Research. L.
Angelses, London, N. Delhi, Singapore, Washington: Sage Publications.
Marvasti, Armin, B. (2004.) Qualitative Research in Sociolgy. London. Thousend Oaks, New
Dehli: Sage Publications.

Mataušić, Juraj Mirko (2007.) „Komunikacijske znanosti: Definicije i područja istraživanja“,
u:
Mataušić, Juraj Mirko (ur.). Komunikacijske znanosti: Znanstvene grane i nazivlje. Zagreb:
Hrvatski studiji Sveučilišta u Zagrebu, str. 9-36.
Maxwell, A. Joseph (2012). Qualitative Research Design: An Interacitve Approach.
https://www.researchgate.net/publication/43220402_Qualitative_Research_Design_An
_Interactive_Approach_JA_Maxwell (5. 2. 2018.)
McGuire, J. William (1996.) “The Yale Communication and Attitude-Change Program in
1950”, u: Wartella, E. Dennis i Wartella, Ellen (ur.) American Communication Research. The
Remebered History. New Jersey: Lawrence Erlbaum Associates, str. 39-60.
Mejovšek, Milko (2003.) Uvod u metode znanstvenog istraživanja. Zagreb: Naklada Slap.
Milas, Goran (2009.) Istraživačke metode u psihologiji i drugim društvenim znanostima.
Zagreb: Naklada Slap (2. izdanje).
Miller, G. A. (1956). The magical number seven, plus or minus two: Some limits on our
capacity for processing information. Psychological Review, 63(2), 81–
97. https://doi.org/10.1037/h0043158
Mokyr, Joel (2007.) Atenini darovi. Historijski korijeni ekonomije znanja. Beograd: Clio.
Murphy, D. J. (2002). Surveys and questionnaires. In L. Gurak & M. M. Lay (Eds.), Research
in technical communication (pp. 93-110). Westport, CT: Praeger.
O'Hear, Anthony (2007.) Uvod u filozofiju znanosti. Zagreb: Sveučilište u Zagrebu. Hrvatski
studiji.
Popper, Karl (1973. [1959.]) Logika naučnog otkrića. Beograd: Nolit.
Popper, Karl (2004.) Nedovršena potraga. Zagreb: Algoritam.
Riffe, Daniel, Lacy, Sephen i Fico G. Frederic (2005.) Using Quantitative Content Analysis in
Research. Mahaw, New Jersey, London: Lawrence Erlbaum Associates.

Rubić, Tihana (2013.)“ Nezaposlenost i neformalna ekonomija u Hrvatskoj: analiza
diskursa“, Studia ethnologica Croatica, 25, 61-92.
Rogers, M. Everett (1997.) A History of Communication Study. New York: The Free Press.
Seidman, Irwing (2006.) Interviewing as Qualitative Research. New York: Teachers College
Press.
Sekol, Ivana i Maurović, Ivana (2017.) „Miješanje kvantitativnog i kvalitativnog
istraživačkog pristupa u društvenim znanostima – miješanje metoda ili metodologija?“,
Ljetopis socijalnog rada, 24 (1): 7-32.
Skoko, Božo i Benković, Vanesa (2009.) „Znanstvena metoda fokus grupa – mogućnosti i
načini primjene“, Politička misao, 46 (3): 217 – 236.
Snelson, L., Chareen (2016.) „Qualitative and Mixed Methods Social Media Research: A
Review of the Literature“, International Journal of Qualitative Methods, January-
December, 1–15.
Spasić, Ivana (1998.) Interpretativna sociologija. Beograd: Zavod za udžbenike i nastavna
sredstva.
Strauss, L. Anselm (2003.) Qualitative analysis for social scientists. San Francisco:
University of California.
Supek, Rudi (1981.) Ispitivanje javnog mnijenja. Zagreb: SNL.
Šiber, Ivan (2003.) Politički marketing. Zagreb: Politička Kultura.
Škrbić Alempijević, Nevena, Potkonjak, Sanja i Rubić, Tihana (2016). Misliti etnografski.
Kvalitativni pristupi i metode u etnologiji i kulturnoj antropologiji. Zagreb: FF Press.
Tashakkori, A., & Teddlie, C. (1998). Mixed methodology: Combining qualitative
andquantitative approaches. Thousand Oaks Sage.
Tkalac Verčić, Ana, Sinčić Čorić, Dubravka i Pološki Vokić, Nina (2010.) Priručnik za
metodologiju istraživačkog rada. Zagreb: MEP d.o.o.

Tomić-Koludrović, Inga i Leborić, Anči (2002.) Sociologija životnog stila. Zagreb: Naklada
Jesenski i Turk.
Vujević, Miroslav (2006.) Uvođenje u znanstveni rad u području društvenih znanosti.
Zagreb: Školska knjiga.
Waugh, R. Linda, Catalano, Theresa, Masaeed, Al Khaleed, Hong Do, Thom i Renigar, G.
Paul (2015.) “Critical Discourse Analysis: Definition, Approaches, Relation to Pragmatics,
Critique, and Trends”, u
Weber, Max (1989.) Metodologija društvenih nauka. Zagreb: Globus.
Wiillig, Carla (2016.) Kvalitativna istraživanja u psihologiji. Beograd: Clio.
Wimmer, D. Roger i Dominick, R. Joseph (2010.) Mass Media Research. Belmont, CA:
Wadsworthx.
 Stubbs, M. (1997). Whorf's Children: Critical Comments on Critical Discourse Analysis.
U: Ryan, A. i Wray, A. (ur.) Evolving Models of Language. Milton Keynes: Open University
Press.
 Widdowson, H. G. (2004). Text, Context, Pretext: Critical Issues in Discourse Analysis.
Oxford: Blackwell.
