project:
  type: book
  output-dir: _book

execute:
  freeze: auto

book:
  title: "Metode istraživanja masovne komunikacije"
  subtitle: "Metodološke osnove istraživanja masovne komunikacije u komunikologiji, sociologiji i drugim društvenim znanostima"
  author:
    - Ivan Burić
    - Luka Šikić
  language: hr
  chapters:
    - index.qmd
    - 00_uvod.qmd

    - part: "Temelji znanstvenog istraživanja"
      chapters:
        - 01_osnovna_obiljezja.qmd
        - 02_ciljevi.qmd
        - 03_pseudoznanost.qmd
        - 04_kuhn.qmd
        - 05_sistematizacija.qmd
        - 06_razvoj_komunikologije.qmd
        - 07_metode_istrazivanja.qmd

    - part: "Kvantitativne metode istraživanja u društvenim znanostima"
      chapters:
        - 08_kvantitativne_metode.qmd
        - 09_priprema_kvantitativnih.qmd
        - 10_anketa.qmd
        - 11_analiza_sadrzaja.qmd
        - 12_analiza_sadrzaja_digitalno.qmd
        - 13_analiza_mreza.qmd
        - 14a_deskriptivna_statistika.qmd
        - 14b_statisticko_zakljucivanje.qmd
        - 14c_statisticki_testovi.qmd

    - part: "Kvalitativne metode istraživanja u društvenim znanostima"
      chapters:
        - 15_kvalitativne_metode.qmd
        - 16_priprema_kvalitativnih.qmd
        - 17_intervju.qmd
        - 18_fokus_grupe.qmd
        - 19_utemeljena_teorija.qmd
        - 20_analiza_diskursa.qmd
        - 21_pisanje_izvjestaja.qmd

    - part: "Mješovita metodologija"
      chapters:
        - 22_mjesovita_metodologija.qmd

    - part: "Okvir i perspektive"
      chapters:
        - 23_etika.qmd
        - 24_valjanost.qmd
        - 26_racunalna_drustvena_znanost.qmd

    - 25_literatura.qmd

format:
  html:
    theme: cosmo
    lang: hr
    toc: true
    toc-depth: 3
    number-sections: true
    number-depth: 3
    code-fold: true
    code-tools: true
  pdf:
    documentclass: book
    lang: hr
    number-sections: true
  docx:
    number-sections: true
    lang: hr
