---
title: "Literatura"
---


Aaker, A. David, Kumar, V. Murty i Day, S. George (2008.) *Marketinško
istraživanje*. Ekonomski fakultet: Beograd.

Abercrombie, Nicholas, Hill, Stephen i Turner, Bryan, S. (2008).
*Rječnik sociologije*. Zagreb: Jesenski i Turk.

Afrić, Vjekoslav (1989.) *Struktura sociološke teorije*. Zagreb:
Naprijed.

Bechhofer, F., Paterson, L. (2000). *Principles of Research Design in
Social Sciencies*.London: Routledge

Bickman, Leonard i Rog, J. Debra (1998.) *Handbook of Applied Social
Research Methods*. Thousend Oaks, London, New Delhi: Sage
Publications.

Bilić, Paško (2020.) Sociologija medija. Rutine, tehnologija i moć.
Zagreb: Naklada Jesenski i Turk.

Bradburn, Norman, Sudman, Seymour i Wansink, Brian (2004.) *Asking
questions: The definitive guide to questionnaire design for market
research, political polls, and social and health questionnaires.* San
Francisco: Jossey-Bass A Wiley Imprint.

Bulger, Monica (2012.) „Measuring Media Literacy in a National
Context: Cahllenges of Definition Mehod and Implementation", *Medijske
studije* (3) 6: 83-104.

Churchill, A. Gilbert i Iacobucci, Dawn (2002.) *Marketing Research.
Mehgodological Fonudations*. Mason: South Western.

Creswell, J.W. (2009) *Research Design: Qualitative, quantitative and
mixed method approaches.* Thousand Oaks: SAGE .

Creswell, J. W. i Plano Clark, V. L. (2007.) *Designing and conducting
mix methods research*. Thousand Oaks, London, New Delhi: Sage
Publication.

Daymon, Christine, Immy, Holloway (2002.) *Qualitative Research
Methods in Public Relations and Marketing Communications*. London, New
York: Routledge.

Dilthey, Wilhelm (1980.) *Izgradnja historijskog svijeta u duhovnim
naukama*. Beograd: BIGZ.

Durkheim, Emil (1999.) *Pravila sociološke metode*. Zagreb: Jesenski i
Turk.

Elezović, Almir (2012.) „O čemu pišu novine? Analiza sadržaja
novinskih naslovnica (siječanj -- lipanj 2011.)", *Medijska
istraživanja*, 18 (1): 61-88.

Fairclough, Norman (2003.) Analysing Discourse: Textual Analysis for
Social Research, London: Routledge.

Foddy, William (1993.) *Constructing questions for Interviewing and
Quesgtionnaires.*

Cambridge: Cambridge University Press.

Giacomini, M. K., & Cook, D. J. (2000). Users' guides to the medical
literature XXIII.

Qualitative research in health care B: What are the results and how do
they help me care

for my patients? *Journal of the American Medical Association*, *284*,
478-482.

Geertz, Clifford (1973). *Thick Description: Toward an Interpretive
Theory of Culture*. In *The Interpretation of Cultures* (pp. 3--30).
New York: Basic Books.

Glaser Barney i Strauss, Anselm (1967) *The Discovery of Grounded
Theory. Strategies of Qualitative Research*. New Brunswick. London:
Aldine Transaction.

Halmi, Aleksandar (1996.) *Kvalitativna metodologija u društvenim
znanostima*. Zagreb: Pravni fakultet u Zagrebu.

Halmi, Aleksandar (1999.) *Temelji kvantitativne analize u društvenim
znanostima.* Zagreb: Alinea.

Halmi, Aleksandar i Crnoja, Josip (2003.) „Kvalitativna istraživanja u
društvenim znanostima i humanoj ekologiji", *Socijalna ekologija* (12)
3-4: 195 -- 210.

Hanh, Hans, Neurath, Otto i Carnap, Rudolf (2005.) *Znanstveno
shvaćanje svijeta -- Bečki krug.* Zagreb: Hrvatski studiji sveučilišta
u Zagrebu.

Hesse-Bieber, Nagy, Sharlene (2010.) *Mixed Mehtods Research. Merging
Theory with Pratice*. New York, London: The Guilford Press.

Holsti, R. Ole (1969). Content analysis for fhe social sciences and
humanities. Boston: Addison-Wesley.

Koerber, A., & McMichael, L. (2008). Qualitative Sampling Methods A
Primer for Technical Communicators. *Journal of Business and Technical
Communication*, *22*(4), 454--473.
<https://doi.org/10.1177/1050651908320362>

Krueger, Richard, Casey, Marry Anne (2000.) *Focus Groups: A Practical
Guide for Applied Research*. Thousand Oaks: Sage Publications.

Kuhn, S., Thomas (1999. \[1962.\]) *Struktura znanstvenih revolucija*.
Zagreb: Naklada Jesenski i Turk.

Kunczik, Michael i Zipfel, Astrid (2006.) *Uvod u znanost o medijima i
komunikologiju. Zagreb*: Zaklada Friedrich Ebert.

Jeđud, Ivana: (2007) Alisa u zemlji čuda -- kvalitativna metodologija
i metoda utemeljene teorije. Hrvatska revija za rehabilitacijska
istraživanja. 24 (2): str. 83-101.

Lakić, Igor (2009.) „Modeli analize diskursa novinskih članaka",
*Riječ*, 2: 91-108.

Lalić, Dražen i Kunac, Suzana (1999.) „Televizijski spotovi stranaka u
predizbornim kampanjama u Hrvatskoj 1995. i 1997.", u: Vrcan, Srđan,
Buklijaš, Boris, Lalić, Dražen, Kunac, Suzana, Bulat, Nenad, Štrelov,
Damir *Pakiranje vlasti: Analiza izbora \'95 i \'97*, Zagreb: Alineja.

Lamza Posavec, Vesna (2021.) *Metodologija društvenih istraživanja*.
Temeljni uvidi. Zagreb: Institut društvenih znanosti Ivo Pilar.

Livingstone, Sonia (2004.) „Media literacy and the challenge of new
information and communication technologies" \[online\]. London: LSE
Research Online. Available at: [http://eprints.lse.ac.uk/1017
(1](http://eprints.lse.ac.uk/1017%20%20%20(1). 2. 2018.).

Marshall, Catharine i Rossman, B., Gretchen (2011.) *Designin
Qualitative Research*. L. Angelses, London, N. Delhi, Singapore,
Washington: Sage Publications.

Marvasti, Armin, B. (2004.) *Qualitative Research in Sociolgy.*
London*.* Thousend Oaks, New Dehli: Sage Publications.

Mataušić, Juraj Mirko (2007.) „Komunikacijske znanosti: Definicije i
područja istraživanja", u:

Mataušić, Juraj Mirko (ur.). *Komunikacijske znanosti: Znanstvene
grane i nazivlje*. Zagreb: Hrvatski studiji Sveučilišta u Zagrebu,
str. 9-36.

Maxwell, A. Joseph (2012). Qualitative Research Design: An Interacitve
Approach.
[https://www.researchgate.net/publication/43220402_Qualitative_Research_Design_An_Interactive_Approach_JA_Maxwell
(5](https://www.researchgate.net/publication/43220402_Qualitative_Research_Design_An_Interactive_Approach_JA_Maxwell%20(5).
2. 2018.)

McGuire, J. William (1996.) "The Yale Communication and
Attitude-Change Program in 1950", u: Wartella, E. Dennis i Wartella,
Ellen (ur.) A*merican Communication Research.* *The Remebered
History*. New Jersey: Lawrence Erlbaum Associates, str. 39-60.

Mejovšek, Milko (2003.) *Uvod u metode znanstvenog istraživanja*.
Zagreb: Naklada Slap.

Milas, Goran (2009.) *Istraživačke metode u psihologiji i drugim
društvenim znanostima.* Zagreb: Naklada Slap (2. izdanje).

Miller, G. A. (1956). The magical number seven, plus or minus two:
Some limits on our capacity for processing information. *Psychological
Review, 63*(2),
81--97. [https://doi.org/10.1037/h0043158](https://psycnet.apa.org/doi/10.1037/h0043158)

Mokyr, Joel (2007.) *Atenini darovi*. *Historijski* *korijeni
ekonomije znanja*. Beograd: Clio.

Murphy, D. J. (2002). Surveys and questionnaires. In L. Gurak & M. M.
Lay (Eds.), *Research*

*in technical communication* (pp. 93-110). Westport, CT: Praeger.

O\'Hear, Anthony (2007.) *Uvod u filozofiju znanosti.* Zagreb:
Sveučilište u Zagrebu. Hrvatski studiji.

Popper, Karl (1973. \[1959.\]) *Logika naučnog otkrića*. Beograd:
Nolit.

Popper, Karl (2004.) *Nedovršena potraga*. Zagreb: Algoritam.

Riffe, Daniel, Lacy, Sephen i Fico G. Frederic (2005.) *Using
Quantitative Content Analysis in Research.* Mahaw, New Jersey, London:
Lawrence Erlbaum Associates.

Rubić, Tihana (2013.)" Nezaposlenost i neformalna ekonomija u
Hrvatskoj: analiza diskursa", *Studia ethnologica Croatica*, 25,
61-92.

Rogers, M. Everett (1997.) *A History of Communication Study.* New
York*:* The Free Press.

Seidman, Irwing (2006.) *Interviewing as Qualitative Research.* New
York: Teachers College Press.

Sekol, Ivana i Maurović, Ivana (2017.) „Miješanje kvantitativnog i
kvalitativnog istraživačkog pristupa u društvenim znanostima --
miješanje metoda ili metodologija?", *Ljetopis socijalnog rada*, 24
(1): 7-32.

Skoko, Božo i Benković, Vanesa (2009.) „Znanstvena metoda fokus grupa
-- mogućnosti i načini primjene", *Politička misao*, 46 (3): 217 --
236.

Snelson, L., Chareen (2016.) „Qualitative and Mixed Methods Social
Media Research: A Review of the Literature", *International Journal of
Qualitative Methods, January-December, 1--15.*

Spasić, Ivana (1998.) *Interpretativna sociologija*. Beograd: Zavod za
udžbenike i nastavna sredstva.

Strauss, L. Anselm (2003.) *Qualitative analysis for social
scientists*. San Francisco: University of California.

Supek, Rudi (1981.) *Ispitivanje javnog mnijenja.* Zagreb: SNL.

Šiber, Ivan (2003.) *Politički marketing*. Zagreb: Politička Kultura.

Škrbić Alempijević, Nevena, Potkonjak, Sanja i Rubić, Tihana (2016).
Misliti etnografski. Kvalitativni pristupi i metode u etnologiji i
kulturnoj antropologiji. Zagreb: FF Press.

Tashakkori, A., & Teddlie, C. (1998). *Mixed methodology: Combining
qualitative andquantitative approaches*. Thousand Oaks Sage.

Tkalac Verčić, Ana, Sinčić Čorić, Dubravka i Pološki Vokić, Nina
(2010.) *Priručnik za metodologiju istraživačkog rada*. Zagreb: MEP
d.o.o.

Tomić-Koludrović, Inga i Leborić, Anči (2002.) *Sociologija životnog
stila*. Zagreb: Naklada Jesenski i Turk.

Vujević, Miroslav (2006.) *Uvođenje u znanstveni rad u području
društvenih znanosti*. Zagreb: Školska knjiga.

Waugh, R. Linda, Catalano, Theresa, Masaeed, Al Khaleed, Hong Do, Thom
i Renigar, G. Paul (2015.) "Critical Discourse Analysis: Definition,
Approaches, Relation to Pragmatics, Critique, and Trends", u

Weber, Max (1989.) *Metodologija društvenih nauka*. Zagreb: Globus.

Wiillig, Carla (2016.) *Kvalitativna istraživanja u psihologiji*.
Beograd: Clio.

Wimmer, D. Roger i Dominick, R. Joseph (2010.) *Mass Media Research.*
Belmont, CA: Wadsworthx.

[^1]: <http://www.enciklopedija.hr/natuknica.aspx?id=32687> (20. 11.
2017.)

[^2]: Dostupno na
<https://narodne-novine.nn.hr/clanci/sluzbeni/2009_09_118_2929.html>

[^3]: <http://www.enciklopedija.hr/natuknica.aspx?id=66216>,
prestupljeno 11. 1. 2018.

[^4]: Mokyr propozicijsko znanje definira kao o pojavama i pravilnostima
u prirodi (Mokyr, 2007:18-19)

[^5]: Svoju teoriju razvija temeljem podataka prikupljenih u
istraživanju People\'s Choice, provedenog tijekom predsjedničke
kampanje 1940. godine u državi Ohio.

[^6]: Uređaj je funkcionirao na način da su sudionici istraživanja
pritisnuli zeleni gumb u slučaju kada im se program sviđao, a crveni
u slučaju kada im se nije bi sviđao.

[^7]: Primjerice, istraživanje se provodi u dva vala. U oba vala uzorak
sudionika istraživanja čine iste osobe.

[^8]: Svega je 54 od 600 ispitanika promijenilo mišljenje o tome za koga
će glasati, a samo njih nekoliko to je učinilo pod utjecajem
medijske kampanje.

[^9]: Razlike između kvantiativnih i kvalitativnih metoda istraživanja
detaljno su predočene u tablici br. 2.

[^10]: Uz djelovanje tzv. Bečkog kruga, logički pozitivizam razvijan je
i u okviru tzv. Berlinskog kruga.

[^11]: <http://www.enciklopedija.hr/natuknica.aspx?id=25156> (22. 1.
2018.)

[^12]: Prema Diltheyu priroda vječito ostaje strana i nepoznata, a
duhovno-povijesne pojave mogu se razumjeti. Kod prirodnih znanosti,
tj. „**objašnjavalačkih znanosti**", stvari se promatraju izvana,
postoji distanciranost onoga tko promatra i onoga što se promatra.
Kod duhovnih znanosti ne postoji distanca subjekta i objekta
promatranja. Istraživač se prešutno uživljava u situaciju te ovakva
**ontološka bliskost između onog tko istražuje i onog što se
istražuje** omogućuje **razumijevanje društvenih pojava**.

[^13]: Nasuprot toga, prirodne znanosti moglo bi se opisati na sljedeći
način: prirodne znanosti bave se univerzalnim pojavama /
činjenicama. One činjenicama prilaze izvana i nastoje ih objasniti
pomoću općih principa. Objasniti pojave znači rekonstruirati uzroke
i posljedice. Rekonstrukcija uzroka i posljedica podrazumijeva
spoznaju ponavljajućih pravilnosti. Spoznati ponavljajuće
pravilnosti znači utvrditi zakonitosti.

[^14]: Više o varijablama vidi: Halmi,1999; Tkalac Verčić, Sinčić Čorić,
Pološki Vokić, 2010.

[^15]: Primjerice, nula stupnjeva Celzijusa ne znači da ne postoji
nikakva toplina.

[^16]: Metoda eksperimenta u komunikologiji koristi se manje učestalo od
metode ankete i analize sadržaja. Zbog toga, ali i zbog činjenice da
bi nastavna obrada ove metode zahtijevala povećanje satnice
predviđene za kolegij *Metodologija istraživanja masovne
komunikacije*, njena obrada u nastavi, pa tako niti u ovoj skripti
nije predviđena. Zainteresirani studenti mogu steći uvid u osnovna
obilježja metode eksperimenta u knjizi Gorana Milasa *Istraživačke
metode u psihologiji i drugim društvenim znanostima* (Naklada Slap,
2009).

[^17]: Npr. generalni cilj istraživanja može biti definiran na sljedeći
način: Utvrditi razinu medijske pismenosti u urbanoj populaciji u
dobi od 30 do 50 godina. Polazeći od ovog generalnog cilja
istraživanja mogu se razraditi sljedeći specifični ciljevi: Utvrditi
sposobnost kritičke evaluacije medijskog sadržaja, utvrditi
mogućnost pristupa pojedinim vrstama medijskog sadržaja, utvrditi
mogućnost kreacije pojedinih vrsta medijskog sadržaja. Dakle,
specifični ciljevi istraživanja se obično definiraju kako bi se
njihovom realizacijom realizirao generalni cilj istraživanja.

[^18]: Parametrijskim statističkim procedurama nazivaju se one
statističke procedure koje se temelje na ispunjenju zahtjeva
normalne raspodjele i jednakosti varijanci.

[^19]: Korištenje Likertove ljestvice kao kvazi-intervalne ljestvice
jedna je od dugotrajnih kontroverzi u metodologiji društvenih
znanosti. Naime, iako se čisto tehnički gledajući radi o ordinalnoj
ljestvici, ona se često koristi kao sredstvo „intervalizacije"
ordinalnih kategorija. Ovakvo tretiranje Likertove ljestvice dopušta
korištenje „jačih" metoda statističke analize, posebice različitih
bivarijatnih i multivarijatnih parametrijskih statističkih analiza.
Kada se na ovaj način statistički obrađuju podaci prikupljeni pomoću
Likertove ljestvice potrebno je obratiti pažnju na sve izvedbene
zahtjeve korištenih statističkih analiza. Naime, statističke testovi
„ne vode brigu o tome odakle brojevi dolaze, već je ključni kriterij
njihovog korištenja taj da pretpostavke na kojima se temelje
mogućnosti samog testiranja moraju biti zadovoljene" (Churchill i
Iacobucci, 2002:387)

[^20]: U nekim pristupima konstrukcije semantičkog diferencijala skala
nije „labelirana", tj. kategorije nisu označene brojevima, već je
samo naznačen prostor koji neka kategorija zauzima.

[^21]: [ Vidi ESS istraživanje, upute za postupak centriranja podataka
oko aritmetičkih sredina na ..]{.mark}

[^22]: Npr., Britanski lingvist Norman Fairclough (2005) u razvoju
vlastite metode analize diskursa naglasak stavlja na korištenje
jezika kao alata za uspostavljanje moći i dominacije u javnim
institucijama ili pak općenito u društvu.

[^23]: Willig (2016) ističe da je u središtu tog pristupa konstrukcija
„znanja", tj. da je ovaj pristup fokusiran na izučavanje kako ljudi
kroz upotrebu jezika konstruiraju različite verzije realnosti.

[^24]: Primjerice, Halmi, Belušić i Ogresta (2004) tvrde da postoji
najmanje 57 varijanti analize diskursa.

[^25]: Na to upućuju i Halmi, Belušić i Ogresta kada navode da ne
postoji gotov recept koji o tome kako pristupiti analizi teksta.
Puno je lakše navesti i raspravljati o ključnim temama analize
diskursa nego nekoga naučiti kako pristupiti analizi teksta (Halmi,
Belušić i Ogresta 40: 2004).

[^26]: [Vidi Ivasović Burić]{.mark}

[^27]: Primjerice, ukoliko se istraživanje provodi posredstvom 10
intervjua i ukoliko svaki intervju traje oko sat vremena, to
podrazumijeva cca 130 -- 160 stranica transkripata koje je potrebno
analizirati.

[^28]: [Za detaljnije upoznavanje s procesom kodiranja koje je razvila
Charmatz, pogledati Škrbić Alempijević, Potkonjak i Rubić 2016. str.
53-56.]{.mark}

[^29]: Uz kodiranje, programski paketi za kvalitativnu obradu podatak
pružaju niz drugih funkcionalnosti, npr. analizu relacija između
koncepata i tema, vizualizaciju podataka Vizualizacije (word clouds,
modeli, grafovi) povezivanje citata s teorijskim izvorima, uvoz
podatak iz drugih izvora i sl.

[^30]: Empirijski materijal prije kodiranja -- u sirovom obliku, npr.
originalni iskazi sudionika fokus grupa.
